// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mmult_tile_process_Pipeline_systolic3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        select_ln117_3,
        b_row_major_0_address0,
        b_row_major_0_ce0,
        b_row_major_0_q0,
        b_row_major_1_address0,
        b_row_major_1_ce0,
        b_row_major_1_q0,
        b_row_major_2_address0,
        b_row_major_2_ce0,
        b_row_major_2_q0,
        b_row_major_3_address0,
        b_row_major_3_ce0,
        b_row_major_3_q0,
        select_ln117,
        c_row_major_0_0_address0,
        c_row_major_0_0_ce0,
        c_row_major_0_0_we0,
        c_row_major_0_0_d0,
        c_row_major_0_0_address1,
        c_row_major_0_0_ce1,
        c_row_major_0_0_q1,
        c_row_major_0_1_address0,
        c_row_major_0_1_ce0,
        c_row_major_0_1_we0,
        c_row_major_0_1_d0,
        c_row_major_0_1_address1,
        c_row_major_0_1_ce1,
        c_row_major_0_1_q1,
        c_row_major_0_2_address0,
        c_row_major_0_2_ce0,
        c_row_major_0_2_we0,
        c_row_major_0_2_d0,
        c_row_major_0_2_address1,
        c_row_major_0_2_ce1,
        c_row_major_0_2_q1,
        c_row_major_0_3_address0,
        c_row_major_0_3_ce0,
        c_row_major_0_3_we0,
        c_row_major_0_3_d0,
        c_row_major_0_3_address1,
        c_row_major_0_3_ce1,
        c_row_major_0_3_q1,
        b_col,
        select_ln117_1,
        sext_ln134
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] select_ln117_3;
output  [7:0] b_row_major_0_address0;
output   b_row_major_0_ce0;
input  [7:0] b_row_major_0_q0;
output  [7:0] b_row_major_1_address0;
output   b_row_major_1_ce0;
input  [7:0] b_row_major_1_q0;
output  [7:0] b_row_major_2_address0;
output   b_row_major_2_ce0;
input  [7:0] b_row_major_2_q0;
output  [7:0] b_row_major_3_address0;
output   b_row_major_3_ce0;
input  [7:0] b_row_major_3_q0;
input  [4:0] select_ln117;
output  [5:0] c_row_major_0_0_address0;
output   c_row_major_0_0_ce0;
output   c_row_major_0_0_we0;
output  [15:0] c_row_major_0_0_d0;
output  [5:0] c_row_major_0_0_address1;
output   c_row_major_0_0_ce1;
input  [15:0] c_row_major_0_0_q1;
output  [5:0] c_row_major_0_1_address0;
output   c_row_major_0_1_ce0;
output   c_row_major_0_1_we0;
output  [15:0] c_row_major_0_1_d0;
output  [5:0] c_row_major_0_1_address1;
output   c_row_major_0_1_ce1;
input  [15:0] c_row_major_0_1_q1;
output  [5:0] c_row_major_0_2_address0;
output   c_row_major_0_2_ce0;
output   c_row_major_0_2_we0;
output  [15:0] c_row_major_0_2_d0;
output  [5:0] c_row_major_0_2_address1;
output   c_row_major_0_2_ce1;
input  [15:0] c_row_major_0_2_q1;
output  [5:0] c_row_major_0_3_address0;
output   c_row_major_0_3_ce0;
output   c_row_major_0_3_we0;
output  [15:0] c_row_major_0_3_d0;
output  [5:0] c_row_major_0_3_address1;
output   c_row_major_0_3_ce1;
input  [15:0] c_row_major_0_3_q1;
input  [31:0] b_col;
input  [0:0] select_ln117_1;
input  [7:0] sext_ln134;

reg ap_idle;
reg b_row_major_0_ce0;
reg b_row_major_1_ce0;
reg b_row_major_2_ce0;
reg b_row_major_3_ce0;
reg c_row_major_0_0_ce0;
reg c_row_major_0_0_we0;
reg c_row_major_0_0_ce1;
reg c_row_major_0_1_ce0;
reg c_row_major_0_1_we0;
reg c_row_major_0_1_ce1;
reg c_row_major_0_2_ce0;
reg c_row_major_0_2_we0;
reg c_row_major_0_2_ce1;
reg c_row_major_0_3_ce0;
reg c_row_major_0_3_we0;
reg c_row_major_0_3_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_256_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [15:0] sext_ln134_cast_fu_244_p1;
reg  signed [15:0] sext_ln134_cast_reg_503;
wire   [2:0] lshr_ln1_fu_282_p4;
reg   [2:0] lshr_ln1_reg_515;
reg   [2:0] lshr_ln1_reg_515_pp0_iter1_reg;
wire   [0:0] icmp_ln133_fu_308_p2;
reg   [0:0] icmp_ln133_reg_540;
wire   [0:0] icmp_ln133_1_fu_314_p2;
reg   [0:0] icmp_ln133_1_reg_545;
wire   [0:0] icmp_ln133_2_fu_330_p2;
reg   [0:0] icmp_ln133_2_reg_550;
wire   [0:0] icmp_ln133_3_fu_346_p2;
reg   [0:0] icmp_ln133_3_reg_555;
reg   [5:0] c_row_major_0_0_addr_reg_580;
reg   [5:0] c_row_major_0_0_addr_reg_580_pp0_iter3_reg;
reg   [5:0] c_row_major_0_1_addr_reg_586;
reg   [5:0] c_row_major_0_1_addr_reg_586_pp0_iter3_reg;
reg   [5:0] c_row_major_0_2_addr_reg_592;
reg   [5:0] c_row_major_0_2_addr_reg_592_pp0_iter3_reg;
reg   [5:0] c_row_major_0_3_addr_reg_598;
reg   [5:0] c_row_major_0_3_addr_reg_598_pp0_iter3_reg;
wire   [63:0] zext_ln133_fu_300_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln126_5_fu_443_p1;
reg   [5:0] j_fu_90;
wire   [5:0] add_ln123_fu_352_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_3;
wire   [15:0] grp_fu_451_p3;
wire   [15:0] grp_fu_459_p3;
wire   [15:0] grp_fu_467_p3;
wire   [15:0] grp_fu_475_p3;
wire   [4:0] trunc_ln123_fu_264_p1;
wire   [4:0] or_ln123_fu_272_p2;
wire   [7:0] tmp_4_fu_292_p3;
wire   [31:0] zext_ln123_fu_268_p1;
wire   [31:0] zext_ln123_1_fu_278_p1;
wire   [4:0] or_ln123_1_fu_320_p2;
wire   [31:0] zext_ln126_fu_326_p1;
wire   [4:0] or_ln123_2_fu_336_p2;
wire   [31:0] zext_ln126_1_fu_342_p1;
wire   [0:0] and_ln133_fu_363_p2;
wire  signed [7:0] b_val_fu_367_p3;
wire   [0:0] and_ln133_1_fu_379_p2;
wire  signed [7:0] b_val_11_fu_383_p3;
wire   [0:0] and_ln133_2_fu_395_p2;
wire  signed [7:0] b_val_12_fu_399_p3;
wire   [0:0] and_ln133_3_fu_411_p2;
wire  signed [7:0] b_val_13_fu_415_p3;
wire   [2:0] tmp_5_fu_427_p4;
wire   [5:0] tmp_6_fu_436_p3;
wire  signed [7:0] grp_fu_451_p1;
wire  signed [7:0] grp_fu_459_p1;
wire  signed [7:0] grp_fu_467_p1;
wire  signed [7:0] grp_fu_475_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 j_fu_90 = 6'd0;
#0 ap_done_reg = 1'b0;
end

mmult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_val_fu_367_p3),
    .din1(grp_fu_451_p1),
    .din2(c_row_major_0_0_q1),
    .ce(1'b1),
    .dout(grp_fu_451_p3)
);

mmult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_val_11_fu_383_p3),
    .din1(grp_fu_459_p1),
    .din2(c_row_major_0_1_q1),
    .ce(1'b1),
    .dout(grp_fu_459_p3)
);

mmult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_val_12_fu_399_p3),
    .din1(grp_fu_467_p1),
    .din2(c_row_major_0_2_q1),
    .ce(1'b1),
    .dout(grp_fu_467_p3)
);

mmult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_val_13_fu_415_p3),
    .din1(grp_fu_475_p1),
    .din2(c_row_major_0_3_q1),
    .ce(1'b1),
    .dout(grp_fu_475_p3)
);

mmult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_256_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_90 <= add_ln123_fu_352_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_90 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln133_1_reg_545 <= icmp_ln133_1_fu_314_p2;
        icmp_ln133_2_reg_550 <= icmp_ln133_2_fu_330_p2;
        icmp_ln133_3_reg_555 <= icmp_ln133_3_fu_346_p2;
        icmp_ln133_reg_540 <= icmp_ln133_fu_308_p2;
        lshr_ln1_reg_515 <= {{ap_sig_allocacmp_j_3[4:2]}};
        lshr_ln1_reg_515_pp0_iter1_reg <= lshr_ln1_reg_515;
        sext_ln134_cast_reg_503 <= sext_ln134_cast_fu_244_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        c_row_major_0_0_addr_reg_580 <= zext_ln126_5_fu_443_p1;
        c_row_major_0_0_addr_reg_580_pp0_iter3_reg <= c_row_major_0_0_addr_reg_580;
        c_row_major_0_1_addr_reg_586 <= zext_ln126_5_fu_443_p1;
        c_row_major_0_1_addr_reg_586_pp0_iter3_reg <= c_row_major_0_1_addr_reg_586;
        c_row_major_0_2_addr_reg_592 <= zext_ln126_5_fu_443_p1;
        c_row_major_0_2_addr_reg_592_pp0_iter3_reg <= c_row_major_0_2_addr_reg_592;
        c_row_major_0_3_addr_reg_598 <= zext_ln126_5_fu_443_p1;
        c_row_major_0_3_addr_reg_598_pp0_iter3_reg <= c_row_major_0_3_addr_reg_598;
    end
end

always @ (*) begin
    if (((tmp_fu_256_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_3 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_row_major_0_ce0 = 1'b1;
    end else begin
        b_row_major_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_row_major_1_ce0 = 1'b1;
    end else begin
        b_row_major_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_row_major_2_ce0 = 1'b1;
    end else begin
        b_row_major_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_row_major_3_ce0 = 1'b1;
    end else begin
        b_row_major_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_0_ce0 = 1'b1;
    end else begin
        c_row_major_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        c_row_major_0_0_ce1 = 1'b1;
    end else begin
        c_row_major_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_0_we0 = 1'b1;
    end else begin
        c_row_major_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_1_ce0 = 1'b1;
    end else begin
        c_row_major_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        c_row_major_0_1_ce1 = 1'b1;
    end else begin
        c_row_major_0_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_1_we0 = 1'b1;
    end else begin
        c_row_major_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_2_ce0 = 1'b1;
    end else begin
        c_row_major_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        c_row_major_0_2_ce1 = 1'b1;
    end else begin
        c_row_major_0_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_2_we0 = 1'b1;
    end else begin
        c_row_major_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_3_ce0 = 1'b1;
    end else begin
        c_row_major_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        c_row_major_0_3_ce1 = 1'b1;
    end else begin
        c_row_major_0_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c_row_major_0_3_we0 = 1'b1;
    end else begin
        c_row_major_0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_fu_352_p2 = (ap_sig_allocacmp_j_3 + 6'd4);

assign and_ln133_1_fu_379_p2 = (select_ln117_1 & icmp_ln133_1_reg_545);

assign and_ln133_2_fu_395_p2 = (select_ln117_1 & icmp_ln133_2_reg_550);

assign and_ln133_3_fu_411_p2 = (select_ln117_1 & icmp_ln133_3_reg_555);

assign and_ln133_fu_363_p2 = (select_ln117_1 & icmp_ln133_reg_540);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_row_major_0_address0 = zext_ln133_fu_300_p1;

assign b_row_major_1_address0 = zext_ln133_fu_300_p1;

assign b_row_major_2_address0 = zext_ln133_fu_300_p1;

assign b_row_major_3_address0 = zext_ln133_fu_300_p1;

assign b_val_11_fu_383_p3 = ((and_ln133_1_fu_379_p2[0:0] == 1'b1) ? b_row_major_1_q0 : 8'd0);

assign b_val_12_fu_399_p3 = ((and_ln133_2_fu_395_p2[0:0] == 1'b1) ? b_row_major_2_q0 : 8'd0);

assign b_val_13_fu_415_p3 = ((and_ln133_3_fu_411_p2[0:0] == 1'b1) ? b_row_major_3_q0 : 8'd0);

assign b_val_fu_367_p3 = ((and_ln133_fu_363_p2[0:0] == 1'b1) ? b_row_major_0_q0 : 8'd0);

assign c_row_major_0_0_address0 = c_row_major_0_0_addr_reg_580_pp0_iter3_reg;

assign c_row_major_0_0_address1 = zext_ln126_5_fu_443_p1;

assign c_row_major_0_0_d0 = grp_fu_451_p3;

assign c_row_major_0_1_address0 = c_row_major_0_1_addr_reg_586_pp0_iter3_reg;

assign c_row_major_0_1_address1 = zext_ln126_5_fu_443_p1;

assign c_row_major_0_1_d0 = grp_fu_459_p3;

assign c_row_major_0_2_address0 = c_row_major_0_2_addr_reg_592_pp0_iter3_reg;

assign c_row_major_0_2_address1 = zext_ln126_5_fu_443_p1;

assign c_row_major_0_2_d0 = grp_fu_467_p3;

assign c_row_major_0_3_address0 = c_row_major_0_3_addr_reg_598_pp0_iter3_reg;

assign c_row_major_0_3_address1 = zext_ln126_5_fu_443_p1;

assign c_row_major_0_3_d0 = grp_fu_475_p3;

assign grp_fu_451_p1 = sext_ln134_cast_reg_503;

assign grp_fu_459_p1 = sext_ln134_cast_reg_503;

assign grp_fu_467_p1 = sext_ln134_cast_reg_503;

assign grp_fu_475_p1 = sext_ln134_cast_reg_503;

assign icmp_ln133_1_fu_314_p2 = (($signed(zext_ln123_1_fu_278_p1) < $signed(b_col)) ? 1'b1 : 1'b0);

assign icmp_ln133_2_fu_330_p2 = (($signed(zext_ln126_fu_326_p1) < $signed(b_col)) ? 1'b1 : 1'b0);

assign icmp_ln133_3_fu_346_p2 = (($signed(zext_ln126_1_fu_342_p1) < $signed(b_col)) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_308_p2 = (($signed(zext_ln123_fu_268_p1) < $signed(b_col)) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_282_p4 = {{ap_sig_allocacmp_j_3[4:2]}};

assign or_ln123_1_fu_320_p2 = (trunc_ln123_fu_264_p1 | 5'd2);

assign or_ln123_2_fu_336_p2 = (trunc_ln123_fu_264_p1 | 5'd3);

assign or_ln123_fu_272_p2 = (trunc_ln123_fu_264_p1 | 5'd1);

assign sext_ln134_cast_fu_244_p1 = $signed(sext_ln134);

assign tmp_4_fu_292_p3 = {{select_ln117_3}, {lshr_ln1_fu_282_p4}};

assign tmp_5_fu_427_p4 = {{select_ln117[4:2]}};

assign tmp_6_fu_436_p3 = {{tmp_5_fu_427_p4}, {lshr_ln1_reg_515_pp0_iter1_reg}};

assign tmp_fu_256_p3 = ap_sig_allocacmp_j_3[32'd5];

assign trunc_ln123_fu_264_p1 = ap_sig_allocacmp_j_3[4:0];

assign zext_ln123_1_fu_278_p1 = or_ln123_fu_272_p2;

assign zext_ln123_fu_268_p1 = ap_sig_allocacmp_j_3;

assign zext_ln126_1_fu_342_p1 = or_ln123_2_fu_336_p2;

assign zext_ln126_5_fu_443_p1 = tmp_6_fu_436_p3;

assign zext_ln126_fu_326_p1 = or_ln123_1_fu_320_p2;

assign zext_ln133_fu_300_p1 = tmp_4_fu_292_p3;

endmodule //mmult_tile_process_Pipeline_systolic3
