// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mmult_mmult_Pipeline_VITIS_LOOP_195_1_VITIS_LOOP_196_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        localC_address0,
        localC_ce0,
        localC_we0,
        localC_d0,
        localC_1_address0,
        localC_1_ce0,
        localC_1_we0,
        localC_1_d0,
        localC_2_address0,
        localC_2_ce0,
        localC_2_we0,
        localC_2_d0,
        localC_3_address0,
        localC_3_ce0,
        localC_3_we0,
        localC_3_d0,
        localC_4_address0,
        localC_4_ce0,
        localC_4_we0,
        localC_4_d0,
        localC_5_address0,
        localC_5_ce0,
        localC_5_we0,
        localC_5_d0,
        localC_6_address0,
        localC_6_ce0,
        localC_6_we0,
        localC_6_d0,
        localC_7_address0,
        localC_7_ce0,
        localC_7_we0,
        localC_7_d0,
        localC_8_address0,
        localC_8_ce0,
        localC_8_we0,
        localC_8_d0,
        localC_9_address0,
        localC_9_ce0,
        localC_9_we0,
        localC_9_d0,
        localC_10_address0,
        localC_10_ce0,
        localC_10_we0,
        localC_10_d0,
        localC_11_address0,
        localC_11_ce0,
        localC_11_we0,
        localC_11_d0,
        localC_12_address0,
        localC_12_ce0,
        localC_12_we0,
        localC_12_d0,
        localC_13_address0,
        localC_13_ce0,
        localC_13_we0,
        localC_13_d0,
        localC_14_address0,
        localC_14_ce0,
        localC_14_we0,
        localC_14_d0,
        localC_15_address0,
        localC_15_ce0,
        localC_15_we0,
        localC_15_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] localC_address0;
output   localC_ce0;
output   localC_we0;
output  [15:0] localC_d0;
output  [5:0] localC_1_address0;
output   localC_1_ce0;
output   localC_1_we0;
output  [15:0] localC_1_d0;
output  [5:0] localC_2_address0;
output   localC_2_ce0;
output   localC_2_we0;
output  [15:0] localC_2_d0;
output  [5:0] localC_3_address0;
output   localC_3_ce0;
output   localC_3_we0;
output  [15:0] localC_3_d0;
output  [5:0] localC_4_address0;
output   localC_4_ce0;
output   localC_4_we0;
output  [15:0] localC_4_d0;
output  [5:0] localC_5_address0;
output   localC_5_ce0;
output   localC_5_we0;
output  [15:0] localC_5_d0;
output  [5:0] localC_6_address0;
output   localC_6_ce0;
output   localC_6_we0;
output  [15:0] localC_6_d0;
output  [5:0] localC_7_address0;
output   localC_7_ce0;
output   localC_7_we0;
output  [15:0] localC_7_d0;
output  [5:0] localC_8_address0;
output   localC_8_ce0;
output   localC_8_we0;
output  [15:0] localC_8_d0;
output  [5:0] localC_9_address0;
output   localC_9_ce0;
output   localC_9_we0;
output  [15:0] localC_9_d0;
output  [5:0] localC_10_address0;
output   localC_10_ce0;
output   localC_10_we0;
output  [15:0] localC_10_d0;
output  [5:0] localC_11_address0;
output   localC_11_ce0;
output   localC_11_we0;
output  [15:0] localC_11_d0;
output  [5:0] localC_12_address0;
output   localC_12_ce0;
output   localC_12_we0;
output  [15:0] localC_12_d0;
output  [5:0] localC_13_address0;
output   localC_13_ce0;
output   localC_13_we0;
output  [15:0] localC_13_d0;
output  [5:0] localC_14_address0;
output   localC_14_ce0;
output   localC_14_we0;
output  [15:0] localC_14_d0;
output  [5:0] localC_15_address0;
output   localC_15_ce0;
output   localC_15_we0;
output  [15:0] localC_15_d0;

reg ap_idle;
reg localC_ce0;
reg localC_we0;
reg localC_1_ce0;
reg localC_1_we0;
reg localC_2_ce0;
reg localC_2_we0;
reg localC_3_ce0;
reg localC_3_we0;
reg localC_4_ce0;
reg localC_4_we0;
reg localC_5_ce0;
reg localC_5_we0;
reg localC_6_ce0;
reg localC_6_we0;
reg localC_7_ce0;
reg localC_7_we0;
reg localC_8_ce0;
reg localC_8_we0;
reg localC_9_ce0;
reg localC_9_we0;
reg localC_10_ce0;
reg localC_10_we0;
reg localC_11_ce0;
reg localC_11_we0;
reg localC_12_ce0;
reg localC_12_we0;
reg localC_13_ce0;
reg localC_13_we0;
reg localC_14_ce0;
reg localC_14_we0;
reg localC_15_ce0;
reg localC_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln195_fu_338_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] trunc_ln195_fu_386_p1;
reg   [1:0] trunc_ln195_reg_481;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] lshr_ln3_reg_485;
reg   [2:0] tmp_s_reg_490;
wire   [63:0] zext_ln198_fu_437_p1;
wire    ap_block_pp0_stage0;
reg   [5:0] j_9_fu_84;
wire   [5:0] add_ln196_fu_410_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_9_load;
reg   [5:0] i_3_fu_88;
wire   [5:0] select_ln195_1_fu_378_p3;
reg   [5:0] ap_sig_allocacmp_i_3_load;
reg   [8:0] indvar_flatten_fu_92;
wire   [8:0] add_ln195_1_fu_344_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] tmp_fu_362_p3;
wire   [5:0] add_ln195_fu_356_p2;
wire   [5:0] select_ln195_fu_370_p3;
wire   [5:0] tmp_4_fu_431_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_9_fu_84 = 6'd0;
#0 i_3_fu_88 = 6'd0;
#0 indvar_flatten_fu_92 = 9'd0;
#0 ap_done_reg = 1'b0;
end

mmult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln195_fu_338_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_3_fu_88 <= select_ln195_1_fu_378_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_3_fu_88 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln195_fu_338_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_92 <= add_ln195_1_fu_344_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_92 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln195_fu_338_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_9_fu_84 <= add_ln196_fu_410_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_9_fu_84 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln3_reg_485 <= {{select_ln195_fu_370_p3[4:2]}};
        tmp_s_reg_490 <= {{select_ln195_1_fu_378_p3[4:2]}};
        trunc_ln195_reg_481 <= trunc_ln195_fu_386_p1;
    end
end

always @ (*) begin
    if (((icmp_ln195_fu_338_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_3_load = i_3_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_9_load = 6'd0;
    end else begin
        ap_sig_allocacmp_j_9_load = j_9_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_10_ce0 = 1'b1;
    end else begin
        localC_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd2))) begin
        localC_10_we0 = 1'b1;
    end else begin
        localC_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_11_ce0 = 1'b1;
    end else begin
        localC_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd2))) begin
        localC_11_we0 = 1'b1;
    end else begin
        localC_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_12_ce0 = 1'b1;
    end else begin
        localC_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd3))) begin
        localC_12_we0 = 1'b1;
    end else begin
        localC_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_13_ce0 = 1'b1;
    end else begin
        localC_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd3))) begin
        localC_13_we0 = 1'b1;
    end else begin
        localC_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_14_ce0 = 1'b1;
    end else begin
        localC_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd3))) begin
        localC_14_we0 = 1'b1;
    end else begin
        localC_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_15_ce0 = 1'b1;
    end else begin
        localC_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd3))) begin
        localC_15_we0 = 1'b1;
    end else begin
        localC_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_1_ce0 = 1'b1;
    end else begin
        localC_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd0))) begin
        localC_1_we0 = 1'b1;
    end else begin
        localC_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_2_ce0 = 1'b1;
    end else begin
        localC_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd0))) begin
        localC_2_we0 = 1'b1;
    end else begin
        localC_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_3_ce0 = 1'b1;
    end else begin
        localC_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd0))) begin
        localC_3_we0 = 1'b1;
    end else begin
        localC_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_4_ce0 = 1'b1;
    end else begin
        localC_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd1))) begin
        localC_4_we0 = 1'b1;
    end else begin
        localC_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_5_ce0 = 1'b1;
    end else begin
        localC_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd1))) begin
        localC_5_we0 = 1'b1;
    end else begin
        localC_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_6_ce0 = 1'b1;
    end else begin
        localC_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd1))) begin
        localC_6_we0 = 1'b1;
    end else begin
        localC_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_7_ce0 = 1'b1;
    end else begin
        localC_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd1))) begin
        localC_7_we0 = 1'b1;
    end else begin
        localC_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_8_ce0 = 1'b1;
    end else begin
        localC_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd2))) begin
        localC_8_we0 = 1'b1;
    end else begin
        localC_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_9_ce0 = 1'b1;
    end else begin
        localC_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd2))) begin
        localC_9_we0 = 1'b1;
    end else begin
        localC_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_ce0 = 1'b1;
    end else begin
        localC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln195_reg_481 == 2'd0))) begin
        localC_we0 = 1'b1;
    end else begin
        localC_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln195_1_fu_344_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln195_fu_356_p2 = (ap_sig_allocacmp_i_3_load + 6'd1);

assign add_ln196_fu_410_p2 = (select_ln195_fu_370_p3 + 6'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln195_fu_338_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd256) ? 1'b1 : 1'b0);

assign localC_10_address0 = zext_ln198_fu_437_p1;

assign localC_10_d0 = 16'd0;

assign localC_11_address0 = zext_ln198_fu_437_p1;

assign localC_11_d0 = 16'd0;

assign localC_12_address0 = zext_ln198_fu_437_p1;

assign localC_12_d0 = 16'd0;

assign localC_13_address0 = zext_ln198_fu_437_p1;

assign localC_13_d0 = 16'd0;

assign localC_14_address0 = zext_ln198_fu_437_p1;

assign localC_14_d0 = 16'd0;

assign localC_15_address0 = zext_ln198_fu_437_p1;

assign localC_15_d0 = 16'd0;

assign localC_1_address0 = zext_ln198_fu_437_p1;

assign localC_1_d0 = 16'd0;

assign localC_2_address0 = zext_ln198_fu_437_p1;

assign localC_2_d0 = 16'd0;

assign localC_3_address0 = zext_ln198_fu_437_p1;

assign localC_3_d0 = 16'd0;

assign localC_4_address0 = zext_ln198_fu_437_p1;

assign localC_4_d0 = 16'd0;

assign localC_5_address0 = zext_ln198_fu_437_p1;

assign localC_5_d0 = 16'd0;

assign localC_6_address0 = zext_ln198_fu_437_p1;

assign localC_6_d0 = 16'd0;

assign localC_7_address0 = zext_ln198_fu_437_p1;

assign localC_7_d0 = 16'd0;

assign localC_8_address0 = zext_ln198_fu_437_p1;

assign localC_8_d0 = 16'd0;

assign localC_9_address0 = zext_ln198_fu_437_p1;

assign localC_9_d0 = 16'd0;

assign localC_address0 = zext_ln198_fu_437_p1;

assign localC_d0 = 16'd0;

assign select_ln195_1_fu_378_p3 = ((tmp_fu_362_p3[0:0] == 1'b1) ? add_ln195_fu_356_p2 : ap_sig_allocacmp_i_3_load);

assign select_ln195_fu_370_p3 = ((tmp_fu_362_p3[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_j_9_load);

assign tmp_4_fu_431_p3 = {{tmp_s_reg_490}, {lshr_ln3_reg_485}};

assign tmp_fu_362_p3 = ap_sig_allocacmp_j_9_load[32'd5];

assign trunc_ln195_fu_386_p1 = select_ln195_1_fu_378_p3[1:0];

assign zext_ln198_fu_437_p1 = tmp_4_fu_431_p3;

endmodule //mmult_mmult_Pipeline_VITIS_LOOP_195_1_VITIS_LOOP_196_2
