// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mmult_tile_process (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_row_major_0_address0,
        a_row_major_0_ce0,
        a_row_major_0_q0,
        a_row_major_1_address0,
        a_row_major_1_ce0,
        a_row_major_1_q0,
        a_row_major_2_address0,
        a_row_major_2_ce0,
        a_row_major_2_q0,
        a_row_major_3_address0,
        a_row_major_3_ce0,
        a_row_major_3_q0,
        b_row_major_0_address0,
        b_row_major_0_ce0,
        b_row_major_0_q0,
        b_row_major_1_address0,
        b_row_major_1_ce0,
        b_row_major_1_q0,
        b_row_major_2_address0,
        b_row_major_2_ce0,
        b_row_major_2_q0,
        b_row_major_3_address0,
        b_row_major_3_ce0,
        b_row_major_3_q0,
        c_row_major_0_0_address0,
        c_row_major_0_0_ce0,
        c_row_major_0_0_we0,
        c_row_major_0_0_d0,
        c_row_major_0_0_address1,
        c_row_major_0_0_ce1,
        c_row_major_0_0_q1,
        c_row_major_0_1_address0,
        c_row_major_0_1_ce0,
        c_row_major_0_1_we0,
        c_row_major_0_1_d0,
        c_row_major_0_1_address1,
        c_row_major_0_1_ce1,
        c_row_major_0_1_q1,
        c_row_major_0_2_address0,
        c_row_major_0_2_ce0,
        c_row_major_0_2_we0,
        c_row_major_0_2_d0,
        c_row_major_0_2_address1,
        c_row_major_0_2_ce1,
        c_row_major_0_2_q1,
        c_row_major_0_3_address0,
        c_row_major_0_3_ce0,
        c_row_major_0_3_we0,
        c_row_major_0_3_d0,
        c_row_major_0_3_address1,
        c_row_major_0_3_ce1,
        c_row_major_0_3_q1,
        c_row_major_1_0_address0,
        c_row_major_1_0_ce0,
        c_row_major_1_0_we0,
        c_row_major_1_0_d0,
        c_row_major_1_0_address1,
        c_row_major_1_0_ce1,
        c_row_major_1_0_q1,
        c_row_major_1_1_address0,
        c_row_major_1_1_ce0,
        c_row_major_1_1_we0,
        c_row_major_1_1_d0,
        c_row_major_1_1_address1,
        c_row_major_1_1_ce1,
        c_row_major_1_1_q1,
        c_row_major_1_2_address0,
        c_row_major_1_2_ce0,
        c_row_major_1_2_we0,
        c_row_major_1_2_d0,
        c_row_major_1_2_address1,
        c_row_major_1_2_ce1,
        c_row_major_1_2_q1,
        c_row_major_1_3_address0,
        c_row_major_1_3_ce0,
        c_row_major_1_3_we0,
        c_row_major_1_3_d0,
        c_row_major_1_3_address1,
        c_row_major_1_3_ce1,
        c_row_major_1_3_q1,
        c_row_major_2_0_address0,
        c_row_major_2_0_ce0,
        c_row_major_2_0_we0,
        c_row_major_2_0_d0,
        c_row_major_2_0_address1,
        c_row_major_2_0_ce1,
        c_row_major_2_0_q1,
        c_row_major_2_1_address0,
        c_row_major_2_1_ce0,
        c_row_major_2_1_we0,
        c_row_major_2_1_d0,
        c_row_major_2_1_address1,
        c_row_major_2_1_ce1,
        c_row_major_2_1_q1,
        c_row_major_2_2_address0,
        c_row_major_2_2_ce0,
        c_row_major_2_2_we0,
        c_row_major_2_2_d0,
        c_row_major_2_2_address1,
        c_row_major_2_2_ce1,
        c_row_major_2_2_q1,
        c_row_major_2_3_address0,
        c_row_major_2_3_ce0,
        c_row_major_2_3_we0,
        c_row_major_2_3_d0,
        c_row_major_2_3_address1,
        c_row_major_2_3_ce1,
        c_row_major_2_3_q1,
        c_row_major_3_0_address0,
        c_row_major_3_0_ce0,
        c_row_major_3_0_we0,
        c_row_major_3_0_d0,
        c_row_major_3_0_address1,
        c_row_major_3_0_ce1,
        c_row_major_3_0_q1,
        c_row_major_3_1_address0,
        c_row_major_3_1_ce0,
        c_row_major_3_1_we0,
        c_row_major_3_1_d0,
        c_row_major_3_1_address1,
        c_row_major_3_1_ce1,
        c_row_major_3_1_q1,
        c_row_major_3_2_address0,
        c_row_major_3_2_ce0,
        c_row_major_3_2_we0,
        c_row_major_3_2_d0,
        c_row_major_3_2_address1,
        c_row_major_3_2_ce1,
        c_row_major_3_2_q1,
        c_row_major_3_3_address0,
        c_row_major_3_3_ce0,
        c_row_major_3_3_we0,
        c_row_major_3_3_d0,
        c_row_major_3_3_address1,
        c_row_major_3_3_ce1,
        c_row_major_3_3_q1,
        start_k,
        finish_k,
        a_row,
        a_col,
        b_col
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_row_major_0_address0;
output   a_row_major_0_ce0;
input  [7:0] a_row_major_0_q0;
output  [7:0] a_row_major_1_address0;
output   a_row_major_1_ce0;
input  [7:0] a_row_major_1_q0;
output  [7:0] a_row_major_2_address0;
output   a_row_major_2_ce0;
input  [7:0] a_row_major_2_q0;
output  [7:0] a_row_major_3_address0;
output   a_row_major_3_ce0;
input  [7:0] a_row_major_3_q0;
output  [7:0] b_row_major_0_address0;
output   b_row_major_0_ce0;
input  [7:0] b_row_major_0_q0;
output  [7:0] b_row_major_1_address0;
output   b_row_major_1_ce0;
input  [7:0] b_row_major_1_q0;
output  [7:0] b_row_major_2_address0;
output   b_row_major_2_ce0;
input  [7:0] b_row_major_2_q0;
output  [7:0] b_row_major_3_address0;
output   b_row_major_3_ce0;
input  [7:0] b_row_major_3_q0;
output  [5:0] c_row_major_0_0_address0;
output   c_row_major_0_0_ce0;
output   c_row_major_0_0_we0;
output  [15:0] c_row_major_0_0_d0;
output  [5:0] c_row_major_0_0_address1;
output   c_row_major_0_0_ce1;
input  [15:0] c_row_major_0_0_q1;
output  [5:0] c_row_major_0_1_address0;
output   c_row_major_0_1_ce0;
output   c_row_major_0_1_we0;
output  [15:0] c_row_major_0_1_d0;
output  [5:0] c_row_major_0_1_address1;
output   c_row_major_0_1_ce1;
input  [15:0] c_row_major_0_1_q1;
output  [5:0] c_row_major_0_2_address0;
output   c_row_major_0_2_ce0;
output   c_row_major_0_2_we0;
output  [15:0] c_row_major_0_2_d0;
output  [5:0] c_row_major_0_2_address1;
output   c_row_major_0_2_ce1;
input  [15:0] c_row_major_0_2_q1;
output  [5:0] c_row_major_0_3_address0;
output   c_row_major_0_3_ce0;
output   c_row_major_0_3_we0;
output  [15:0] c_row_major_0_3_d0;
output  [5:0] c_row_major_0_3_address1;
output   c_row_major_0_3_ce1;
input  [15:0] c_row_major_0_3_q1;
output  [5:0] c_row_major_1_0_address0;
output   c_row_major_1_0_ce0;
output   c_row_major_1_0_we0;
output  [15:0] c_row_major_1_0_d0;
output  [5:0] c_row_major_1_0_address1;
output   c_row_major_1_0_ce1;
input  [15:0] c_row_major_1_0_q1;
output  [5:0] c_row_major_1_1_address0;
output   c_row_major_1_1_ce0;
output   c_row_major_1_1_we0;
output  [15:0] c_row_major_1_1_d0;
output  [5:0] c_row_major_1_1_address1;
output   c_row_major_1_1_ce1;
input  [15:0] c_row_major_1_1_q1;
output  [5:0] c_row_major_1_2_address0;
output   c_row_major_1_2_ce0;
output   c_row_major_1_2_we0;
output  [15:0] c_row_major_1_2_d0;
output  [5:0] c_row_major_1_2_address1;
output   c_row_major_1_2_ce1;
input  [15:0] c_row_major_1_2_q1;
output  [5:0] c_row_major_1_3_address0;
output   c_row_major_1_3_ce0;
output   c_row_major_1_3_we0;
output  [15:0] c_row_major_1_3_d0;
output  [5:0] c_row_major_1_3_address1;
output   c_row_major_1_3_ce1;
input  [15:0] c_row_major_1_3_q1;
output  [5:0] c_row_major_2_0_address0;
output   c_row_major_2_0_ce0;
output   c_row_major_2_0_we0;
output  [15:0] c_row_major_2_0_d0;
output  [5:0] c_row_major_2_0_address1;
output   c_row_major_2_0_ce1;
input  [15:0] c_row_major_2_0_q1;
output  [5:0] c_row_major_2_1_address0;
output   c_row_major_2_1_ce0;
output   c_row_major_2_1_we0;
output  [15:0] c_row_major_2_1_d0;
output  [5:0] c_row_major_2_1_address1;
output   c_row_major_2_1_ce1;
input  [15:0] c_row_major_2_1_q1;
output  [5:0] c_row_major_2_2_address0;
output   c_row_major_2_2_ce0;
output   c_row_major_2_2_we0;
output  [15:0] c_row_major_2_2_d0;
output  [5:0] c_row_major_2_2_address1;
output   c_row_major_2_2_ce1;
input  [15:0] c_row_major_2_2_q1;
output  [5:0] c_row_major_2_3_address0;
output   c_row_major_2_3_ce0;
output   c_row_major_2_3_we0;
output  [15:0] c_row_major_2_3_d0;
output  [5:0] c_row_major_2_3_address1;
output   c_row_major_2_3_ce1;
input  [15:0] c_row_major_2_3_q1;
output  [5:0] c_row_major_3_0_address0;
output   c_row_major_3_0_ce0;
output   c_row_major_3_0_we0;
output  [15:0] c_row_major_3_0_d0;
output  [5:0] c_row_major_3_0_address1;
output   c_row_major_3_0_ce1;
input  [15:0] c_row_major_3_0_q1;
output  [5:0] c_row_major_3_1_address0;
output   c_row_major_3_1_ce0;
output   c_row_major_3_1_we0;
output  [15:0] c_row_major_3_1_d0;
output  [5:0] c_row_major_3_1_address1;
output   c_row_major_3_1_ce1;
input  [15:0] c_row_major_3_1_q1;
output  [5:0] c_row_major_3_2_address0;
output   c_row_major_3_2_ce0;
output   c_row_major_3_2_we0;
output  [15:0] c_row_major_3_2_d0;
output  [5:0] c_row_major_3_2_address1;
output   c_row_major_3_2_ce1;
input  [15:0] c_row_major_3_2_q1;
output  [5:0] c_row_major_3_3_address0;
output   c_row_major_3_3_ce0;
output   c_row_major_3_3_we0;
output  [15:0] c_row_major_3_3_d0;
output  [5:0] c_row_major_3_3_address1;
output   c_row_major_3_3_ce1;
input  [15:0] c_row_major_3_3_q1;
input  [4:0] start_k;
input  [5:0] finish_k;
input  [31:0] a_row;
input  [31:0] a_col;
input  [31:0] b_col;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg a_row_major_0_ce0;
reg a_row_major_1_ce0;
reg a_row_major_2_ce0;
reg a_row_major_3_ce0;
reg[7:0] b_row_major_0_address0;
reg b_row_major_0_ce0;
reg[7:0] b_row_major_1_address0;
reg b_row_major_1_ce0;
reg[7:0] b_row_major_2_address0;
reg b_row_major_2_ce0;
reg[7:0] b_row_major_3_address0;
reg b_row_major_3_ce0;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [63:0] sext_ln117_fu_336_p1;
reg  signed [63:0] sext_ln117_reg_714;
wire  signed [66:0] bound_fu_372_p1;
reg  signed [66:0] bound_reg_722;
wire   [0:0] tmp_6_fu_417_p3;
reg   [0:0] tmp_6_reg_730;
wire    ap_CS_fsm_state2;
wire   [4:0] empty_17_fu_433_p1;
reg   [4:0] empty_17_reg_735;
wire   [0:0] select_ln117_1_fu_447_p3;
reg   [0:0] select_ln117_1_reg_743;
wire   [0:0] slt_fu_455_p2;
reg   [0:0] slt_reg_751;
wire   [0:0] slt69_fu_460_p2;
reg   [0:0] slt69_reg_756;
wire   [4:0] trunc_ln120_fu_473_p1;
reg   [4:0] trunc_ln120_reg_761;
wire   [7:0] empty_18_fu_513_p2;
reg   [7:0] empty_18_reg_769;
wire   [0:0] slt71_fu_519_p2;
reg   [0:0] slt71_reg_774;
wire   [0:0] slt73_fu_524_p2;
reg   [0:0] slt73_reg_779;
wire   [0:0] slt75_fu_539_p2;
reg   [0:0] slt75_reg_784;
wire   [0:0] slt77_fu_554_p2;
reg   [0:0] slt77_reg_789;
wire   [0:0] select_ln117_2_fu_590_p3;
reg   [0:0] select_ln117_2_reg_794;
wire    ap_CS_fsm_state3;
wire   [7:0] a_val_fu_614_p3;
reg   [7:0] a_val_reg_822;
wire    ap_CS_fsm_state4;
wire   [7:0] a_val_1_fu_633_p3;
reg   [7:0] a_val_1_reg_827;
wire   [7:0] a_val_2_fu_651_p3;
reg   [7:0] a_val_2_reg_832;
wire   [7:0] a_val_3_fu_669_p3;
reg   [7:0] a_val_3_reg_837;
wire    grp_tile_process_Pipeline_systolic3_fu_224_ap_start;
wire    grp_tile_process_Pipeline_systolic3_fu_224_ap_done;
wire    grp_tile_process_Pipeline_systolic3_fu_224_ap_idle;
wire    grp_tile_process_Pipeline_systolic3_fu_224_ap_ready;
wire   [7:0] grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_0_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_0_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_1_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_1_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_2_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_2_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_3_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_3_ce0;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_ce0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_address1;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_ce0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_address1;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_ce0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_address1;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_address0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_ce0;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_address1;
wire    grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_ce1;
wire    grp_tile_process_Pipeline_systolic32_fu_249_ap_start;
wire    grp_tile_process_Pipeline_systolic32_fu_249_ap_done;
wire    grp_tile_process_Pipeline_systolic32_fu_249_ap_idle;
wire    grp_tile_process_Pipeline_systolic32_fu_249_ap_ready;
wire   [7:0] grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_0_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_0_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_1_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_1_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_2_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_2_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_3_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_3_ce0;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_ce0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_address1;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_ce0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_address1;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_ce0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_address1;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_address0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_ce0;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_address1;
wire    grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_ce1;
wire    grp_tile_process_Pipeline_systolic33_fu_274_ap_start;
wire    grp_tile_process_Pipeline_systolic33_fu_274_ap_done;
wire    grp_tile_process_Pipeline_systolic33_fu_274_ap_idle;
wire    grp_tile_process_Pipeline_systolic33_fu_274_ap_ready;
wire   [7:0] grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_0_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_0_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_1_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_1_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_2_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_2_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_3_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_3_ce0;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_ce0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_address1;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_ce0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_address1;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_ce0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_address1;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_address0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_ce0;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_address1;
wire    grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_ce1;
wire    grp_tile_process_Pipeline_systolic34_fu_299_ap_start;
wire    grp_tile_process_Pipeline_systolic34_fu_299_ap_done;
wire    grp_tile_process_Pipeline_systolic34_fu_299_ap_idle;
wire    grp_tile_process_Pipeline_systolic34_fu_299_ap_ready;
wire   [7:0] grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_0_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_0_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_1_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_1_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_2_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_2_ce0;
wire   [7:0] grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_3_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_3_ce0;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_ce0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_address1;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_ce0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_address1;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_ce0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_address1;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_ce1;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_address0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_ce0;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_we0;
wire   [15:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_d0;
wire   [5:0] grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_address1;
wire    grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_ce1;
reg    grp_tile_process_Pipeline_systolic3_fu_224_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_tile_process_Pipeline_systolic32_fu_249_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_tile_process_Pipeline_systolic33_fu_274_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_tile_process_Pipeline_systolic34_fu_299_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire   [63:0] p_cast_fu_597_p1;
reg   [5:0] i_fu_130;
wire   [5:0] add_ln120_fu_559_p2;
wire   [0:0] icmp_ln117_fu_394_p2;
reg   [63:0] k_fu_134;
wire   [63:0] select_ln117_3_fu_465_p3;
wire   [63:0] zext_ln117_fu_324_p1;
reg   [66:0] indvar_flatten_fu_138;
wire   [66:0] add_ln117_1_fu_399_p2;
wire   [5:0] zext_ln117_2_fu_332_p1;
wire   [0:0] empty_fu_340_p2;
wire   [5:0] smax1_fu_346_p3;
wire   [6:0] zext_ln117_3_fu_354_p1;
wire   [6:0] zext_ln117_1_fu_328_p1;
wire   [6:0] sub_ln117_fu_358_p2;
wire   [9:0] tmp_fu_364_p3;
wire   [5:0] select_ln117_fu_425_p3;
wire   [63:0] add_ln117_fu_411_p2;
wire   [0:0] cmp17_mid1_fu_437_p2;
wire   [0:0] cmp172_fu_442_p2;
wire   [4:0] or_ln120_fu_485_p2;
wire   [2:0] lshr_ln_fu_495_p4;
wire   [7:0] tmp_2_fu_505_p3;
wire   [7:0] trunc_ln120_1_fu_477_p1;
wire   [31:0] zext_ln120_fu_481_p1;
wire   [31:0] zext_ln120_1_fu_491_p1;
wire   [4:0] or_ln120_1_fu_529_p2;
wire   [31:0] or_ln120_1_cast_fu_535_p1;
wire   [4:0] or_ln120_2_fu_544_p2;
wire   [31:0] or_ln120_2_cast_fu_550_p1;
wire   [0:0] rev68_fu_580_p2;
wire   [0:0] rev70_fu_585_p2;
wire   [0:0] rev72_fu_604_p2;
wire   [0:0] brmerge_fu_609_p2;
wire   [0:0] rev74_fu_623_p2;
wire   [0:0] brmerge137_fu_628_p2;
wire   [0:0] rev76_fu_641_p2;
wire   [0:0] brmerge152_fu_646_p2;
wire   [0:0] rev78_fu_659_p2;
wire   [0:0] brmerge167_fu_664_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_tile_process_Pipeline_systolic3_fu_224_ap_start_reg = 1'b0;
#0 grp_tile_process_Pipeline_systolic32_fu_249_ap_start_reg = 1'b0;
#0 grp_tile_process_Pipeline_systolic33_fu_274_ap_start_reg = 1'b0;
#0 grp_tile_process_Pipeline_systolic34_fu_299_ap_start_reg = 1'b0;
#0 i_fu_130 = 6'd0;
#0 k_fu_134 = 64'd0;
#0 indvar_flatten_fu_138 = 67'd0;
end

mmult_tile_process_Pipeline_systolic3 grp_tile_process_Pipeline_systolic3_fu_224(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tile_process_Pipeline_systolic3_fu_224_ap_start),
    .ap_done(grp_tile_process_Pipeline_systolic3_fu_224_ap_done),
    .ap_idle(grp_tile_process_Pipeline_systolic3_fu_224_ap_idle),
    .ap_ready(grp_tile_process_Pipeline_systolic3_fu_224_ap_ready),
    .select_ln117_3(trunc_ln120_reg_761),
    .b_row_major_0_address0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_0_address0),
    .b_row_major_0_ce0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_0_ce0),
    .b_row_major_0_q0(b_row_major_0_q0),
    .b_row_major_1_address0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_1_address0),
    .b_row_major_1_ce0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_1_ce0),
    .b_row_major_1_q0(b_row_major_1_q0),
    .b_row_major_2_address0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_2_address0),
    .b_row_major_2_ce0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_2_ce0),
    .b_row_major_2_q0(b_row_major_2_q0),
    .b_row_major_3_address0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_3_address0),
    .b_row_major_3_ce0(grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_3_ce0),
    .b_row_major_3_q0(b_row_major_3_q0),
    .select_ln117(empty_17_reg_735),
    .c_row_major_0_0_address0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_address0),
    .c_row_major_0_0_ce0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_ce0),
    .c_row_major_0_0_we0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_we0),
    .c_row_major_0_0_d0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_d0),
    .c_row_major_0_0_address1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_address1),
    .c_row_major_0_0_ce1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_ce1),
    .c_row_major_0_0_q1(c_row_major_0_0_q1),
    .c_row_major_0_1_address0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_address0),
    .c_row_major_0_1_ce0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_ce0),
    .c_row_major_0_1_we0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_we0),
    .c_row_major_0_1_d0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_d0),
    .c_row_major_0_1_address1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_address1),
    .c_row_major_0_1_ce1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_ce1),
    .c_row_major_0_1_q1(c_row_major_0_1_q1),
    .c_row_major_0_2_address0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_address0),
    .c_row_major_0_2_ce0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_ce0),
    .c_row_major_0_2_we0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_we0),
    .c_row_major_0_2_d0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_d0),
    .c_row_major_0_2_address1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_address1),
    .c_row_major_0_2_ce1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_ce1),
    .c_row_major_0_2_q1(c_row_major_0_2_q1),
    .c_row_major_0_3_address0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_address0),
    .c_row_major_0_3_ce0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_ce0),
    .c_row_major_0_3_we0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_we0),
    .c_row_major_0_3_d0(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_d0),
    .c_row_major_0_3_address1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_address1),
    .c_row_major_0_3_ce1(grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_ce1),
    .c_row_major_0_3_q1(c_row_major_0_3_q1),
    .b_col(b_col),
    .select_ln117_1(select_ln117_1_reg_743),
    .sext_ln134(a_val_reg_822)
);

mmult_tile_process_Pipeline_systolic32 grp_tile_process_Pipeline_systolic32_fu_249(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tile_process_Pipeline_systolic32_fu_249_ap_start),
    .ap_done(grp_tile_process_Pipeline_systolic32_fu_249_ap_done),
    .ap_idle(grp_tile_process_Pipeline_systolic32_fu_249_ap_idle),
    .ap_ready(grp_tile_process_Pipeline_systolic32_fu_249_ap_ready),
    .select_ln117_3(trunc_ln120_reg_761),
    .b_row_major_0_address0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_0_address0),
    .b_row_major_0_ce0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_0_ce0),
    .b_row_major_0_q0(b_row_major_0_q0),
    .b_row_major_1_address0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_1_address0),
    .b_row_major_1_ce0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_1_ce0),
    .b_row_major_1_q0(b_row_major_1_q0),
    .b_row_major_2_address0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_2_address0),
    .b_row_major_2_ce0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_2_ce0),
    .b_row_major_2_q0(b_row_major_2_q0),
    .b_row_major_3_address0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_3_address0),
    .b_row_major_3_ce0(grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_3_ce0),
    .b_row_major_3_q0(b_row_major_3_q0),
    .select_ln117(empty_17_reg_735),
    .c_row_major_1_0_address0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_address0),
    .c_row_major_1_0_ce0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_ce0),
    .c_row_major_1_0_we0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_we0),
    .c_row_major_1_0_d0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_d0),
    .c_row_major_1_0_address1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_address1),
    .c_row_major_1_0_ce1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_ce1),
    .c_row_major_1_0_q1(c_row_major_1_0_q1),
    .c_row_major_1_1_address0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_address0),
    .c_row_major_1_1_ce0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_ce0),
    .c_row_major_1_1_we0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_we0),
    .c_row_major_1_1_d0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_d0),
    .c_row_major_1_1_address1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_address1),
    .c_row_major_1_1_ce1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_ce1),
    .c_row_major_1_1_q1(c_row_major_1_1_q1),
    .c_row_major_1_2_address0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_address0),
    .c_row_major_1_2_ce0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_ce0),
    .c_row_major_1_2_we0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_we0),
    .c_row_major_1_2_d0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_d0),
    .c_row_major_1_2_address1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_address1),
    .c_row_major_1_2_ce1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_ce1),
    .c_row_major_1_2_q1(c_row_major_1_2_q1),
    .c_row_major_1_3_address0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_address0),
    .c_row_major_1_3_ce0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_ce0),
    .c_row_major_1_3_we0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_we0),
    .c_row_major_1_3_d0(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_d0),
    .c_row_major_1_3_address1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_address1),
    .c_row_major_1_3_ce1(grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_ce1),
    .c_row_major_1_3_q1(c_row_major_1_3_q1),
    .b_col(b_col),
    .select_ln117_1(select_ln117_1_reg_743),
    .sext_ln134_3(a_val_1_reg_827)
);

mmult_tile_process_Pipeline_systolic33 grp_tile_process_Pipeline_systolic33_fu_274(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tile_process_Pipeline_systolic33_fu_274_ap_start),
    .ap_done(grp_tile_process_Pipeline_systolic33_fu_274_ap_done),
    .ap_idle(grp_tile_process_Pipeline_systolic33_fu_274_ap_idle),
    .ap_ready(grp_tile_process_Pipeline_systolic33_fu_274_ap_ready),
    .select_ln117_3(trunc_ln120_reg_761),
    .b_row_major_0_address0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_0_address0),
    .b_row_major_0_ce0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_0_ce0),
    .b_row_major_0_q0(b_row_major_0_q0),
    .b_row_major_1_address0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_1_address0),
    .b_row_major_1_ce0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_1_ce0),
    .b_row_major_1_q0(b_row_major_1_q0),
    .b_row_major_2_address0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_2_address0),
    .b_row_major_2_ce0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_2_ce0),
    .b_row_major_2_q0(b_row_major_2_q0),
    .b_row_major_3_address0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_3_address0),
    .b_row_major_3_ce0(grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_3_ce0),
    .b_row_major_3_q0(b_row_major_3_q0),
    .select_ln117(empty_17_reg_735),
    .c_row_major_2_0_address0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_address0),
    .c_row_major_2_0_ce0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_ce0),
    .c_row_major_2_0_we0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_we0),
    .c_row_major_2_0_d0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_d0),
    .c_row_major_2_0_address1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_address1),
    .c_row_major_2_0_ce1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_ce1),
    .c_row_major_2_0_q1(c_row_major_2_0_q1),
    .c_row_major_2_1_address0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_address0),
    .c_row_major_2_1_ce0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_ce0),
    .c_row_major_2_1_we0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_we0),
    .c_row_major_2_1_d0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_d0),
    .c_row_major_2_1_address1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_address1),
    .c_row_major_2_1_ce1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_ce1),
    .c_row_major_2_1_q1(c_row_major_2_1_q1),
    .c_row_major_2_2_address0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_address0),
    .c_row_major_2_2_ce0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_ce0),
    .c_row_major_2_2_we0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_we0),
    .c_row_major_2_2_d0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_d0),
    .c_row_major_2_2_address1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_address1),
    .c_row_major_2_2_ce1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_ce1),
    .c_row_major_2_2_q1(c_row_major_2_2_q1),
    .c_row_major_2_3_address0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_address0),
    .c_row_major_2_3_ce0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_ce0),
    .c_row_major_2_3_we0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_we0),
    .c_row_major_2_3_d0(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_d0),
    .c_row_major_2_3_address1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_address1),
    .c_row_major_2_3_ce1(grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_ce1),
    .c_row_major_2_3_q1(c_row_major_2_3_q1),
    .b_col(b_col),
    .select_ln117_1(select_ln117_1_reg_743),
    .sext_ln134_8(a_val_2_reg_832)
);

mmult_tile_process_Pipeline_systolic34 grp_tile_process_Pipeline_systolic34_fu_299(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tile_process_Pipeline_systolic34_fu_299_ap_start),
    .ap_done(grp_tile_process_Pipeline_systolic34_fu_299_ap_done),
    .ap_idle(grp_tile_process_Pipeline_systolic34_fu_299_ap_idle),
    .ap_ready(grp_tile_process_Pipeline_systolic34_fu_299_ap_ready),
    .select_ln117_3(trunc_ln120_reg_761),
    .b_row_major_0_address0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_0_address0),
    .b_row_major_0_ce0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_0_ce0),
    .b_row_major_0_q0(b_row_major_0_q0),
    .b_row_major_1_address0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_1_address0),
    .b_row_major_1_ce0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_1_ce0),
    .b_row_major_1_q0(b_row_major_1_q0),
    .b_row_major_2_address0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_2_address0),
    .b_row_major_2_ce0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_2_ce0),
    .b_row_major_2_q0(b_row_major_2_q0),
    .b_row_major_3_address0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_3_address0),
    .b_row_major_3_ce0(grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_3_ce0),
    .b_row_major_3_q0(b_row_major_3_q0),
    .select_ln117(empty_17_reg_735),
    .c_row_major_3_0_address0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_address0),
    .c_row_major_3_0_ce0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_ce0),
    .c_row_major_3_0_we0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_we0),
    .c_row_major_3_0_d0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_d0),
    .c_row_major_3_0_address1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_address1),
    .c_row_major_3_0_ce1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_ce1),
    .c_row_major_3_0_q1(c_row_major_3_0_q1),
    .c_row_major_3_1_address0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_address0),
    .c_row_major_3_1_ce0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_ce0),
    .c_row_major_3_1_we0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_we0),
    .c_row_major_3_1_d0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_d0),
    .c_row_major_3_1_address1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_address1),
    .c_row_major_3_1_ce1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_ce1),
    .c_row_major_3_1_q1(c_row_major_3_1_q1),
    .c_row_major_3_2_address0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_address0),
    .c_row_major_3_2_ce0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_ce0),
    .c_row_major_3_2_we0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_we0),
    .c_row_major_3_2_d0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_d0),
    .c_row_major_3_2_address1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_address1),
    .c_row_major_3_2_ce1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_ce1),
    .c_row_major_3_2_q1(c_row_major_3_2_q1),
    .c_row_major_3_3_address0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_address0),
    .c_row_major_3_3_ce0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_ce0),
    .c_row_major_3_3_we0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_we0),
    .c_row_major_3_3_d0(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_d0),
    .c_row_major_3_3_address1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_address1),
    .c_row_major_3_3_ce1(grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_ce1),
    .c_row_major_3_3_q1(c_row_major_3_3_q1),
    .b_col(b_col),
    .select_ln117_1(select_ln117_1_reg_743),
    .sext_ln134_13(a_val_3_reg_837)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tile_process_Pipeline_systolic32_fu_249_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_tile_process_Pipeline_systolic32_fu_249_ap_start_reg <= 1'b1;
        end else if ((grp_tile_process_Pipeline_systolic32_fu_249_ap_ready == 1'b1)) begin
            grp_tile_process_Pipeline_systolic32_fu_249_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tile_process_Pipeline_systolic33_fu_274_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_tile_process_Pipeline_systolic33_fu_274_ap_start_reg <= 1'b1;
        end else if ((grp_tile_process_Pipeline_systolic33_fu_274_ap_ready == 1'b1)) begin
            grp_tile_process_Pipeline_systolic33_fu_274_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tile_process_Pipeline_systolic34_fu_299_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_tile_process_Pipeline_systolic34_fu_299_ap_start_reg <= 1'b1;
        end else if ((grp_tile_process_Pipeline_systolic34_fu_299_ap_ready == 1'b1)) begin
            grp_tile_process_Pipeline_systolic34_fu_299_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tile_process_Pipeline_systolic3_fu_224_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_tile_process_Pipeline_systolic3_fu_224_ap_start_reg <= 1'b1;
        end else if ((grp_tile_process_Pipeline_systolic3_fu_224_ap_ready == 1'b1)) begin
            grp_tile_process_Pipeline_systolic3_fu_224_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_130 <= 6'd0;
    end else if (((icmp_ln117_fu_394_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_130 <= add_ln120_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_138 <= 67'd0;
    end else if (((icmp_ln117_fu_394_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_138 <= add_ln117_1_fu_399_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_fu_134 <= zext_ln117_fu_324_p1;
    end else if (((icmp_ln117_fu_394_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        k_fu_134 <= select_ln117_3_fu_465_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        a_val_1_reg_827 <= a_val_1_fu_633_p3;
        a_val_2_reg_832 <= a_val_2_fu_651_p3;
        a_val_3_reg_837 <= a_val_3_fu_669_p3;
        a_val_reg_822 <= a_val_fu_614_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_reg_722[66 : 3] <= bound_fu_372_p1[66 : 3];
        sext_ln117_reg_714 <= sext_ln117_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_17_reg_735 <= empty_17_fu_433_p1;
        empty_18_reg_769 <= empty_18_fu_513_p2;
        select_ln117_1_reg_743 <= select_ln117_1_fu_447_p3;
        slt69_reg_756 <= slt69_fu_460_p2;
        slt71_reg_774 <= slt71_fu_519_p2;
        slt73_reg_779 <= slt73_fu_524_p2;
        slt75_reg_784 <= slt75_fu_539_p2;
        slt77_reg_789 <= slt77_fu_554_p2;
        slt_reg_751 <= slt_fu_455_p2;
        tmp_6_reg_730 <= i_fu_130[32'd5];
        trunc_ln120_reg_761 <= trunc_ln120_fu_473_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        select_ln117_2_reg_794 <= select_ln117_2_fu_590_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        a_row_major_0_ce0 = 1'b1;
    end else begin
        a_row_major_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        a_row_major_1_ce0 = 1'b1;
    end else begin
        a_row_major_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        a_row_major_2_ce0 = 1'b1;
    end else begin
        a_row_major_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        a_row_major_3_ce0 = 1'b1;
    end else begin
        a_row_major_3_ce0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_tile_process_Pipeline_systolic34_fu_299_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_tile_process_Pipeline_systolic3_fu_224_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_tile_process_Pipeline_systolic32_fu_249_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_tile_process_Pipeline_systolic33_fu_274_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln117_fu_394_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln117_fu_394_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_0_address0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_0_address0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_0_address0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_0_address0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_0_address0;
    end else begin
        b_row_major_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_0_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_0_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_0_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_0_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_0_ce0;
    end else begin
        b_row_major_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_1_address0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_1_address0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_1_address0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_1_address0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_1_address0;
    end else begin
        b_row_major_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_1_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_1_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_1_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_1_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_1_ce0;
    end else begin
        b_row_major_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_2_address0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_2_address0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_2_address0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_2_address0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_2_address0;
    end else begin
        b_row_major_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_2_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_2_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_2_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_2_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_2_ce0;
    end else begin
        b_row_major_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_3_address0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_3_address0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_3_address0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_3_address0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_3_address0;
    end else begin
        b_row_major_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_row_major_3_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_b_row_major_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        b_row_major_3_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_b_row_major_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        b_row_major_3_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_b_row_major_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        b_row_major_3_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_b_row_major_3_ce0;
    end else begin
        b_row_major_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln117_fu_394_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_tile_process_Pipeline_systolic3_fu_224_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_tile_process_Pipeline_systolic32_fu_249_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_tile_process_Pipeline_systolic33_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_tile_process_Pipeline_systolic34_fu_299_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_row_major_0_address0 = p_cast_fu_597_p1;

assign a_row_major_1_address0 = p_cast_fu_597_p1;

assign a_row_major_2_address0 = p_cast_fu_597_p1;

assign a_row_major_3_address0 = p_cast_fu_597_p1;

assign a_val_1_fu_633_p3 = ((brmerge137_fu_628_p2[0:0] == 1'b1) ? 8'd0 : a_row_major_1_q0);

assign a_val_2_fu_651_p3 = ((brmerge152_fu_646_p2[0:0] == 1'b1) ? 8'd0 : a_row_major_2_q0);

assign a_val_3_fu_669_p3 = ((brmerge167_fu_664_p2[0:0] == 1'b1) ? 8'd0 : a_row_major_3_q0);

assign a_val_fu_614_p3 = ((brmerge_fu_609_p2[0:0] == 1'b1) ? 8'd0 : a_row_major_0_q0);

assign add_ln117_1_fu_399_p2 = (indvar_flatten_fu_138 + 67'd1);

assign add_ln117_fu_411_p2 = (k_fu_134 + 64'd1);

assign add_ln120_fu_559_p2 = (select_ln117_fu_425_p3 + 6'd4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bound_fu_372_p1 = $signed(tmp_fu_364_p3);

assign brmerge137_fu_628_p2 = (select_ln117_2_reg_794 | rev74_fu_623_p2);

assign brmerge152_fu_646_p2 = (select_ln117_2_reg_794 | rev76_fu_641_p2);

assign brmerge167_fu_664_p2 = (select_ln117_2_reg_794 | rev78_fu_659_p2);

assign brmerge_fu_609_p2 = (select_ln117_2_reg_794 | rev72_fu_604_p2);

assign c_row_major_0_0_address0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_address0;

assign c_row_major_0_0_address1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_address1;

assign c_row_major_0_0_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_ce0;

assign c_row_major_0_0_ce1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_ce1;

assign c_row_major_0_0_d0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_d0;

assign c_row_major_0_0_we0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_0_we0;

assign c_row_major_0_1_address0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_address0;

assign c_row_major_0_1_address1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_address1;

assign c_row_major_0_1_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_ce0;

assign c_row_major_0_1_ce1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_ce1;

assign c_row_major_0_1_d0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_d0;

assign c_row_major_0_1_we0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_1_we0;

assign c_row_major_0_2_address0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_address0;

assign c_row_major_0_2_address1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_address1;

assign c_row_major_0_2_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_ce0;

assign c_row_major_0_2_ce1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_ce1;

assign c_row_major_0_2_d0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_d0;

assign c_row_major_0_2_we0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_2_we0;

assign c_row_major_0_3_address0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_address0;

assign c_row_major_0_3_address1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_address1;

assign c_row_major_0_3_ce0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_ce0;

assign c_row_major_0_3_ce1 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_ce1;

assign c_row_major_0_3_d0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_d0;

assign c_row_major_0_3_we0 = grp_tile_process_Pipeline_systolic3_fu_224_c_row_major_0_3_we0;

assign c_row_major_1_0_address0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_address0;

assign c_row_major_1_0_address1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_address1;

assign c_row_major_1_0_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_ce0;

assign c_row_major_1_0_ce1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_ce1;

assign c_row_major_1_0_d0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_d0;

assign c_row_major_1_0_we0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_0_we0;

assign c_row_major_1_1_address0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_address0;

assign c_row_major_1_1_address1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_address1;

assign c_row_major_1_1_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_ce0;

assign c_row_major_1_1_ce1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_ce1;

assign c_row_major_1_1_d0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_d0;

assign c_row_major_1_1_we0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_1_we0;

assign c_row_major_1_2_address0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_address0;

assign c_row_major_1_2_address1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_address1;

assign c_row_major_1_2_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_ce0;

assign c_row_major_1_2_ce1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_ce1;

assign c_row_major_1_2_d0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_d0;

assign c_row_major_1_2_we0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_2_we0;

assign c_row_major_1_3_address0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_address0;

assign c_row_major_1_3_address1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_address1;

assign c_row_major_1_3_ce0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_ce0;

assign c_row_major_1_3_ce1 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_ce1;

assign c_row_major_1_3_d0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_d0;

assign c_row_major_1_3_we0 = grp_tile_process_Pipeline_systolic32_fu_249_c_row_major_1_3_we0;

assign c_row_major_2_0_address0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_address0;

assign c_row_major_2_0_address1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_address1;

assign c_row_major_2_0_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_ce0;

assign c_row_major_2_0_ce1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_ce1;

assign c_row_major_2_0_d0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_d0;

assign c_row_major_2_0_we0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_0_we0;

assign c_row_major_2_1_address0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_address0;

assign c_row_major_2_1_address1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_address1;

assign c_row_major_2_1_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_ce0;

assign c_row_major_2_1_ce1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_ce1;

assign c_row_major_2_1_d0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_d0;

assign c_row_major_2_1_we0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_1_we0;

assign c_row_major_2_2_address0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_address0;

assign c_row_major_2_2_address1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_address1;

assign c_row_major_2_2_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_ce0;

assign c_row_major_2_2_ce1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_ce1;

assign c_row_major_2_2_d0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_d0;

assign c_row_major_2_2_we0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_2_we0;

assign c_row_major_2_3_address0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_address0;

assign c_row_major_2_3_address1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_address1;

assign c_row_major_2_3_ce0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_ce0;

assign c_row_major_2_3_ce1 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_ce1;

assign c_row_major_2_3_d0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_d0;

assign c_row_major_2_3_we0 = grp_tile_process_Pipeline_systolic33_fu_274_c_row_major_2_3_we0;

assign c_row_major_3_0_address0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_address0;

assign c_row_major_3_0_address1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_address1;

assign c_row_major_3_0_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_ce0;

assign c_row_major_3_0_ce1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_ce1;

assign c_row_major_3_0_d0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_d0;

assign c_row_major_3_0_we0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_0_we0;

assign c_row_major_3_1_address0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_address0;

assign c_row_major_3_1_address1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_address1;

assign c_row_major_3_1_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_ce0;

assign c_row_major_3_1_ce1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_ce1;

assign c_row_major_3_1_d0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_d0;

assign c_row_major_3_1_we0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_1_we0;

assign c_row_major_3_2_address0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_address0;

assign c_row_major_3_2_address1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_address1;

assign c_row_major_3_2_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_ce0;

assign c_row_major_3_2_ce1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_ce1;

assign c_row_major_3_2_d0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_d0;

assign c_row_major_3_2_we0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_2_we0;

assign c_row_major_3_3_address0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_address0;

assign c_row_major_3_3_address1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_address1;

assign c_row_major_3_3_ce0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_ce0;

assign c_row_major_3_3_ce1 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_ce1;

assign c_row_major_3_3_d0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_d0;

assign c_row_major_3_3_we0 = grp_tile_process_Pipeline_systolic34_fu_299_c_row_major_3_3_we0;

assign cmp172_fu_442_p2 = (($signed(k_fu_134) < $signed(sext_ln117_reg_714)) ? 1'b1 : 1'b0);

assign cmp17_mid1_fu_437_p2 = (($signed(add_ln117_fu_411_p2) < $signed(sext_ln117_reg_714)) ? 1'b1 : 1'b0);

assign empty_17_fu_433_p1 = select_ln117_fu_425_p3[4:0];

assign empty_18_fu_513_p2 = (tmp_2_fu_505_p3 + trunc_ln120_1_fu_477_p1);

assign empty_fu_340_p2 = ((finish_k > zext_ln117_2_fu_332_p1) ? 1'b1 : 1'b0);

assign grp_tile_process_Pipeline_systolic32_fu_249_ap_start = grp_tile_process_Pipeline_systolic32_fu_249_ap_start_reg;

assign grp_tile_process_Pipeline_systolic33_fu_274_ap_start = grp_tile_process_Pipeline_systolic33_fu_274_ap_start_reg;

assign grp_tile_process_Pipeline_systolic34_fu_299_ap_start = grp_tile_process_Pipeline_systolic34_fu_299_ap_start_reg;

assign grp_tile_process_Pipeline_systolic3_fu_224_ap_start = grp_tile_process_Pipeline_systolic3_fu_224_ap_start_reg;

assign icmp_ln117_fu_394_p2 = ((indvar_flatten_fu_138 == bound_reg_722) ? 1'b1 : 1'b0);

assign lshr_ln_fu_495_p4 = {{select_ln117_fu_425_p3[4:2]}};

assign or_ln120_1_cast_fu_535_p1 = or_ln120_1_fu_529_p2;

assign or_ln120_1_fu_529_p2 = (empty_17_fu_433_p1 | 5'd2);

assign or_ln120_2_cast_fu_550_p1 = or_ln120_2_fu_544_p2;

assign or_ln120_2_fu_544_p2 = (empty_17_fu_433_p1 | 5'd3);

assign or_ln120_fu_485_p2 = (empty_17_fu_433_p1 | 5'd1);

assign p_cast_fu_597_p1 = empty_18_reg_769;

assign rev68_fu_580_p2 = (slt_reg_751 ^ 1'd1);

assign rev70_fu_585_p2 = (slt69_reg_756 ^ 1'd1);

assign rev72_fu_604_p2 = (slt71_reg_774 ^ 1'd1);

assign rev74_fu_623_p2 = (slt73_reg_779 ^ 1'd1);

assign rev76_fu_641_p2 = (slt75_reg_784 ^ 1'd1);

assign rev78_fu_659_p2 = (slt77_reg_789 ^ 1'd1);

assign select_ln117_1_fu_447_p3 = ((tmp_6_fu_417_p3[0:0] == 1'b1) ? cmp17_mid1_fu_437_p2 : cmp172_fu_442_p2);

assign select_ln117_2_fu_590_p3 = ((tmp_6_reg_730[0:0] == 1'b1) ? rev68_fu_580_p2 : rev70_fu_585_p2);

assign select_ln117_3_fu_465_p3 = ((tmp_6_fu_417_p3[0:0] == 1'b1) ? add_ln117_fu_411_p2 : k_fu_134);

assign select_ln117_fu_425_p3 = ((tmp_6_fu_417_p3[0:0] == 1'b1) ? 6'd0 : i_fu_130);

assign sext_ln117_fu_336_p1 = $signed(a_col);

assign slt69_fu_460_p2 = (($signed(k_fu_134) < $signed(sext_ln117_reg_714)) ? 1'b1 : 1'b0);

assign slt71_fu_519_p2 = (($signed(zext_ln120_fu_481_p1) < $signed(a_row)) ? 1'b1 : 1'b0);

assign slt73_fu_524_p2 = (($signed(zext_ln120_1_fu_491_p1) < $signed(a_row)) ? 1'b1 : 1'b0);

assign slt75_fu_539_p2 = (($signed(or_ln120_1_cast_fu_535_p1) < $signed(a_row)) ? 1'b1 : 1'b0);

assign slt77_fu_554_p2 = (($signed(or_ln120_2_cast_fu_550_p1) < $signed(a_row)) ? 1'b1 : 1'b0);

assign slt_fu_455_p2 = (($signed(add_ln117_fu_411_p2) < $signed(sext_ln117_reg_714)) ? 1'b1 : 1'b0);

assign smax1_fu_346_p3 = ((empty_fu_340_p2[0:0] == 1'b1) ? finish_k : zext_ln117_2_fu_332_p1);

assign sub_ln117_fu_358_p2 = (zext_ln117_3_fu_354_p1 - zext_ln117_1_fu_328_p1);

assign tmp_2_fu_505_p3 = {{lshr_ln_fu_495_p4}, {5'd0}};

assign tmp_6_fu_417_p3 = i_fu_130[32'd5];

assign tmp_fu_364_p3 = {{sub_ln117_fu_358_p2}, {3'd0}};

assign trunc_ln120_1_fu_477_p1 = select_ln117_3_fu_465_p3[7:0];

assign trunc_ln120_fu_473_p1 = select_ln117_3_fu_465_p3[4:0];

assign zext_ln117_1_fu_328_p1 = start_k;

assign zext_ln117_2_fu_332_p1 = start_k;

assign zext_ln117_3_fu_354_p1 = smax1_fu_346_p3;

assign zext_ln117_fu_324_p1 = start_k;

assign zext_ln120_1_fu_491_p1 = or_ln120_fu_485_p2;

assign zext_ln120_fu_481_p1 = select_ln117_fu_425_p3;

always @ (posedge ap_clk) begin
    bound_reg_722[2:0] <= 3'b000;
end

endmodule //mmult_tile_process
