-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mmult_Loop_writeC_proc_Pipeline_writeC is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mul36 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_WREADY : IN STD_LOGIC;
    m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RVALID : IN STD_LOGIC;
    m_axi_gmem2_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem2_RLAST : IN STD_LOGIC;
    m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BVALID : IN STD_LOGIC;
    m_axi_gmem2_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln240 : IN STD_LOGIC_VECTOR (62 downto 0);
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    localC_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_ce0 : OUT STD_LOGIC;
    localC_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_1_ce0 : OUT STD_LOGIC;
    localC_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_2_ce0 : OUT STD_LOGIC;
    localC_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_3_ce0 : OUT STD_LOGIC;
    localC_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_4_ce0 : OUT STD_LOGIC;
    localC_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_5_ce0 : OUT STD_LOGIC;
    localC_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_6_ce0 : OUT STD_LOGIC;
    localC_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_7_ce0 : OUT STD_LOGIC;
    localC_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_8_ce0 : OUT STD_LOGIC;
    localC_8_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_9_ce0 : OUT STD_LOGIC;
    localC_9_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_10_ce0 : OUT STD_LOGIC;
    localC_10_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_11_ce0 : OUT STD_LOGIC;
    localC_11_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_12_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_12_ce0 : OUT STD_LOGIC;
    localC_12_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_13_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_13_ce0 : OUT STD_LOGIC;
    localC_13_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_14_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_14_ce0 : OUT STD_LOGIC;
    localC_14_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    localC_15_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    localC_15_ce0 : OUT STD_LOGIC;
    localC_15_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of mmult_Loop_writeC_proc_Pipeline_writeC is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln240_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem2_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln240_reg_666 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal j_load_reg_670 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln242_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln242_reg_680 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln242_fu_427_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln242_reg_685 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln_reg_690 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln240_fu_464_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln240_reg_695 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_607_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_reg_783 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln246_fu_484_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal j_fu_114 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal j_5_fu_504_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_1_fu_419_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal loc_fu_122 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln240_fu_391_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln240_fu_382_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln243_fu_413_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_4_fu_458_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_451_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln3_fu_468_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln246_fu_478_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_515_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_538_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_561_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_584_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_515_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_538_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_561_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_584_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_607_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal tmp_fu_515_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_515_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_515_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_515_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_538_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_538_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_538_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_538_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_561_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_561_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_561_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_561_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_584_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_584_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_584_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_584_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_607_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_607_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_607_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_607_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mmult_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component mmult_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_16_1_1_U218 : component mmult_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => localC_q0,
        din1 => localC_1_q0,
        din2 => localC_2_q0,
        din3 => localC_3_q0,
        def => tmp_fu_515_p9,
        sel => trunc_ln240_reg_695,
        dout => tmp_fu_515_p11);

    sparsemux_9_2_16_1_1_U219 : component mmult_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => localC_4_q0,
        din1 => localC_5_q0,
        din2 => localC_6_q0,
        din3 => localC_7_q0,
        def => tmp_1_fu_538_p9,
        sel => trunc_ln240_reg_695,
        dout => tmp_1_fu_538_p11);

    sparsemux_9_2_16_1_1_U220 : component mmult_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => localC_8_q0,
        din1 => localC_9_q0,
        din2 => localC_10_q0,
        din3 => localC_11_q0,
        def => tmp_2_fu_561_p9,
        sel => trunc_ln240_reg_695,
        dout => tmp_2_fu_561_p11);

    sparsemux_9_2_16_1_1_U221 : component mmult_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => localC_12_q0,
        din1 => localC_13_q0,
        din2 => localC_14_q0,
        din3 => localC_15_q0,
        def => tmp_3_fu_584_p9,
        sel => trunc_ln240_reg_695,
        dout => tmp_3_fu_584_p11);

    sparsemux_9_2_16_1_1_U222 : component mmult_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => tmp_fu_515_p11,
        din1 => tmp_1_fu_538_p11,
        din2 => tmp_2_fu_561_p11,
        din3 => tmp_3_fu_584_p11,
        def => tmp_4_fu_607_p9,
        sel => trunc_ln242_reg_685,
        dout => tmp_4_fu_607_p11);

    flow_control_loop_pipe_sequential_init_U : component mmult_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    i_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_fu_118 <= ap_const_lv32_0;
            elsif (((icmp_ln240_fu_386_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                i_fu_118 <= i_1_fu_419_p3;
            end if; 
        end if;
    end process;

    j_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_114 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln240_reg_666 = ap_const_lv1_1))) then 
                    j_fu_114 <= j_5_fu_504_p2;
                end if;
            end if; 
        end if;
    end process;

    loc_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                loc_fu_122 <= ap_const_lv31_0;
            elsif (((icmp_ln240_fu_386_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                loc_fu_122 <= add_ln240_fu_391_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln240_reg_666 <= icmp_ln240_fu_386_p2;
                icmp_ln242_reg_680 <= icmp_ln242_fu_408_p2;
                j_load_reg_670 <= j_fu_114;
                lshr_ln_reg_690 <= i_1_fu_419_p3(4 downto 2);
                tmp_4_reg_783 <= tmp_4_fu_607_p11;
                trunc_ln242_reg_685 <= trunc_ln242_fu_427_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln240_reg_695 <= trunc_ln240_fu_464_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0, ap_idle_pp0_0to0, ap_idle_pp0_1to2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln240_fu_391_p2 <= std_logic_vector(unsigned(loc_fu_122) + unsigned(ap_const_lv31_1));
    add_ln243_fu_413_p2 <= std_logic_vector(unsigned(i_fu_118) + unsigned(ap_const_lv32_1));
    add_ln246_fu_478_p2 <= std_logic_vector(unsigned(tmp_s_fu_451_p3) + unsigned(lshr_ln3_fu_468_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem2_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem2_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln240_fu_386_p2)
    begin
        if (((icmp_ln240_fu_386_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln240_reg_666, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln240_reg_666 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gmem2_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, m_axi_gmem2_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem2_blk_n_W <= m_axi_gmem2_WREADY;
        else 
            gmem2_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    i_1_fu_419_p3 <= 
        add_ln243_fu_413_p2 when (icmp_ln242_fu_408_p2(0) = '1') else 
        i_fu_118;
    icmp_ln240_fu_386_p2 <= "1" when (signed(zext_ln240_fu_382_p1) < signed(mul36)) else "0";
    icmp_ln242_fu_408_p2 <= "1" when (j_fu_114 = p_read) else "0";
    j_4_fu_458_p3 <= 
        ap_const_lv32_0 when (icmp_ln242_reg_680(0) = '1') else 
        j_load_reg_670;
    j_5_fu_504_p2 <= std_logic_vector(unsigned(j_4_fu_458_p3) + unsigned(ap_const_lv32_1));
    localC_10_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_10_ce0 <= ap_const_logic_1;
        else 
            localC_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_11_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_11_ce0 <= ap_const_logic_1;
        else 
            localC_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_12_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_12_ce0 <= ap_const_logic_1;
        else 
            localC_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_13_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_13_ce0 <= ap_const_logic_1;
        else 
            localC_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_14_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_14_ce0 <= ap_const_logic_1;
        else 
            localC_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_15_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_15_ce0 <= ap_const_logic_1;
        else 
            localC_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_1_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_1_ce0 <= ap_const_logic_1;
        else 
            localC_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_2_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_2_ce0 <= ap_const_logic_1;
        else 
            localC_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_3_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_3_ce0 <= ap_const_logic_1;
        else 
            localC_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_4_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_4_ce0 <= ap_const_logic_1;
        else 
            localC_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_5_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_5_ce0 <= ap_const_logic_1;
        else 
            localC_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_6_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_6_ce0 <= ap_const_logic_1;
        else 
            localC_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_7_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_7_ce0 <= ap_const_logic_1;
        else 
            localC_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_8_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_8_ce0 <= ap_const_logic_1;
        else 
            localC_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_9_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_9_ce0 <= ap_const_logic_1;
        else 
            localC_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localC_address0 <= zext_ln246_fu_484_p1(6 - 1 downto 0);

    localC_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            localC_ce0 <= ap_const_logic_1;
        else 
            localC_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln3_fu_468_p4 <= j_4_fu_458_p3(7 downto 2);
    m_axi_gmem2_ARADDR <= ap_const_lv64_0;
    m_axi_gmem2_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_ARID <= ap_const_lv1_0;
    m_axi_gmem2_ARLEN <= ap_const_lv32_0;
    m_axi_gmem2_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_ARUSER <= ap_const_lv1_0;
    m_axi_gmem2_ARVALID <= ap_const_logic_0;
    m_axi_gmem2_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_AWID <= ap_const_lv1_0;
    m_axi_gmem2_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_BREADY <= ap_const_logic_0;
    m_axi_gmem2_RREADY <= ap_const_logic_0;
    m_axi_gmem2_WDATA <= tmp_4_reg_783;
    m_axi_gmem2_WID <= ap_const_lv1_0;
    m_axi_gmem2_WLAST <= ap_const_logic_0;
    m_axi_gmem2_WSTRB <= ap_const_lv2_3;
    m_axi_gmem2_WUSER <= ap_const_lv1_0;

    m_axi_gmem2_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem2_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem2_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_538_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_2_fu_561_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_3_fu_584_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_4_fu_607_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_fu_515_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_s_fu_451_p3 <= (lshr_ln_reg_690 & ap_const_lv3_0);
    trunc_ln240_fu_464_p1 <= j_4_fu_458_p3(2 - 1 downto 0);
    trunc_ln242_fu_427_p1 <= i_1_fu_419_p3(2 - 1 downto 0);
    zext_ln240_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loc_fu_122),32));
    zext_ln246_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln246_fu_478_p2),64));
end behav;
