-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mmult_Loop_readA_proc_Pipeline_readA is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    localA_62_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_62_ce1 : OUT STD_LOGIC;
    localA_62_we1 : OUT STD_LOGIC;
    localA_62_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_61_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_61_ce1 : OUT STD_LOGIC;
    localA_61_we1 : OUT STD_LOGIC;
    localA_61_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_60_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_60_ce1 : OUT STD_LOGIC;
    localA_60_we1 : OUT STD_LOGIC;
    localA_60_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_59_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_59_ce1 : OUT STD_LOGIC;
    localA_59_we1 : OUT STD_LOGIC;
    localA_59_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_58_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_58_ce1 : OUT STD_LOGIC;
    localA_58_we1 : OUT STD_LOGIC;
    localA_58_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_57_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_57_ce1 : OUT STD_LOGIC;
    localA_57_we1 : OUT STD_LOGIC;
    localA_57_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_56_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_56_ce1 : OUT STD_LOGIC;
    localA_56_we1 : OUT STD_LOGIC;
    localA_56_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_55_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_55_ce1 : OUT STD_LOGIC;
    localA_55_we1 : OUT STD_LOGIC;
    localA_55_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_54_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_54_ce1 : OUT STD_LOGIC;
    localA_54_we1 : OUT STD_LOGIC;
    localA_54_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_53_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_53_ce1 : OUT STD_LOGIC;
    localA_53_we1 : OUT STD_LOGIC;
    localA_53_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_52_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_52_ce1 : OUT STD_LOGIC;
    localA_52_we1 : OUT STD_LOGIC;
    localA_52_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_51_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_51_ce1 : OUT STD_LOGIC;
    localA_51_we1 : OUT STD_LOGIC;
    localA_51_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_50_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_50_ce1 : OUT STD_LOGIC;
    localA_50_we1 : OUT STD_LOGIC;
    localA_50_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_49_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_49_ce1 : OUT STD_LOGIC;
    localA_49_we1 : OUT STD_LOGIC;
    localA_49_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_48_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_48_ce1 : OUT STD_LOGIC;
    localA_48_we1 : OUT STD_LOGIC;
    localA_48_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_47_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_47_ce1 : OUT STD_LOGIC;
    localA_47_we1 : OUT STD_LOGIC;
    localA_47_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_46_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_46_ce1 : OUT STD_LOGIC;
    localA_46_we1 : OUT STD_LOGIC;
    localA_46_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_45_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_45_ce1 : OUT STD_LOGIC;
    localA_45_we1 : OUT STD_LOGIC;
    localA_45_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_44_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_44_ce1 : OUT STD_LOGIC;
    localA_44_we1 : OUT STD_LOGIC;
    localA_44_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_43_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_43_ce1 : OUT STD_LOGIC;
    localA_43_we1 : OUT STD_LOGIC;
    localA_43_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_42_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_42_ce1 : OUT STD_LOGIC;
    localA_42_we1 : OUT STD_LOGIC;
    localA_42_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_41_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_41_ce1 : OUT STD_LOGIC;
    localA_41_we1 : OUT STD_LOGIC;
    localA_41_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_40_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_40_ce1 : OUT STD_LOGIC;
    localA_40_we1 : OUT STD_LOGIC;
    localA_40_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_39_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_39_ce1 : OUT STD_LOGIC;
    localA_39_we1 : OUT STD_LOGIC;
    localA_39_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_38_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_38_ce1 : OUT STD_LOGIC;
    localA_38_we1 : OUT STD_LOGIC;
    localA_38_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_37_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_37_ce1 : OUT STD_LOGIC;
    localA_37_we1 : OUT STD_LOGIC;
    localA_37_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_36_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_36_ce1 : OUT STD_LOGIC;
    localA_36_we1 : OUT STD_LOGIC;
    localA_36_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_35_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_35_ce1 : OUT STD_LOGIC;
    localA_35_we1 : OUT STD_LOGIC;
    localA_35_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_34_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_34_ce1 : OUT STD_LOGIC;
    localA_34_we1 : OUT STD_LOGIC;
    localA_34_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_33_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_33_ce1 : OUT STD_LOGIC;
    localA_33_we1 : OUT STD_LOGIC;
    localA_33_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_32_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_32_ce1 : OUT STD_LOGIC;
    localA_32_we1 : OUT STD_LOGIC;
    localA_32_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    localA_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    localA_ce1 : OUT STD_LOGIC;
    localA_we1 : OUT STD_LOGIC;
    localA_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    mul : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    a : IN STD_LOGIC_VECTOR (63 downto 0);
    a_col : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of mmult_Loop_readA_proc_Pipeline_readA is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln175_fu_783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln175_reg_924 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal add_ln175_fu_788_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln175_reg_928 : STD_LOGIC_VECTOR (30 downto 0);
    signal j_load_reg_933 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln177_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln177_reg_943 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_3_fu_816_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_3_reg_948 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln175_fu_824_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln175_reg_953 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_4_fu_828_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_4_reg_957 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem0_addr_read_reg_962 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln181_fu_853_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal i_fu_182 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_186 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal j_5_fu_834_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal loc_fu_190 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_predicate_pred445_state4 : BOOLEAN;
    signal ap_predicate_pred450_state4 : BOOLEAN;
    signal ap_predicate_pred455_state4 : BOOLEAN;
    signal ap_predicate_pred460_state4 : BOOLEAN;
    signal ap_predicate_pred465_state4 : BOOLEAN;
    signal ap_predicate_pred470_state4 : BOOLEAN;
    signal ap_predicate_pred475_state4 : BOOLEAN;
    signal ap_predicate_pred480_state4 : BOOLEAN;
    signal ap_predicate_pred485_state4 : BOOLEAN;
    signal ap_predicate_pred490_state4 : BOOLEAN;
    signal ap_predicate_pred495_state4 : BOOLEAN;
    signal ap_predicate_pred500_state4 : BOOLEAN;
    signal ap_predicate_pred505_state4 : BOOLEAN;
    signal ap_predicate_pred510_state4 : BOOLEAN;
    signal ap_predicate_pred515_state4 : BOOLEAN;
    signal ap_predicate_pred520_state4 : BOOLEAN;
    signal ap_predicate_pred525_state4 : BOOLEAN;
    signal ap_predicate_pred530_state4 : BOOLEAN;
    signal ap_predicate_pred535_state4 : BOOLEAN;
    signal ap_predicate_pred540_state4 : BOOLEAN;
    signal ap_predicate_pred545_state4 : BOOLEAN;
    signal ap_predicate_pred550_state4 : BOOLEAN;
    signal ap_predicate_pred555_state4 : BOOLEAN;
    signal ap_predicate_pred560_state4 : BOOLEAN;
    signal ap_predicate_pred565_state4 : BOOLEAN;
    signal ap_predicate_pred570_state4 : BOOLEAN;
    signal ap_predicate_pred575_state4 : BOOLEAN;
    signal ap_predicate_pred580_state4 : BOOLEAN;
    signal ap_predicate_pred585_state4 : BOOLEAN;
    signal ap_predicate_pred590_state4 : BOOLEAN;
    signal ap_predicate_pred595_state4 : BOOLEAN;
    signal ap_predicate_pred600_state4 : BOOLEAN;
    signal zext_ln175_fu_779_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln178_fu_810_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mmult_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mmult_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_182 <= ap_const_lv32_0;
                elsif (((icmp_ln175_reg_924 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_182 <= i_3_reg_948;
                end if;
            end if; 
        end if;
    end process;

    j_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_186 <= ap_const_lv32_0;
                elsif (((icmp_ln175_reg_924 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    j_fu_186 <= j_5_fu_834_p2;
                end if;
            end if; 
        end if;
    end process;

    loc_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    loc_fu_190 <= ap_const_lv31_0;
                elsif (((icmp_ln175_reg_924 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    loc_fu_190 <= add_ln175_reg_928;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln175_reg_928 <= add_ln175_fu_788_p2;
                i_3_reg_948 <= i_3_fu_816_p3;
                icmp_ln175_reg_924 <= icmp_ln175_fu_783_p2;
                icmp_ln177_reg_943 <= icmp_ln177_fu_805_p2;
                j_load_reg_933 <= j_fu_186;
                trunc_ln175_reg_953 <= trunc_ln175_fu_824_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    ap_predicate_pred445_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_1E);
                    ap_predicate_pred450_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_1D);
                    ap_predicate_pred455_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_1C);
                    ap_predicate_pred460_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_1B);
                    ap_predicate_pred465_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_1A);
                    ap_predicate_pred470_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_19);
                    ap_predicate_pred475_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_18);
                    ap_predicate_pred480_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_17);
                    ap_predicate_pred485_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_16);
                    ap_predicate_pred490_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_15);
                    ap_predicate_pred495_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_14);
                    ap_predicate_pred500_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_13);
                    ap_predicate_pred505_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_12);
                    ap_predicate_pred510_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_11);
                    ap_predicate_pred515_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_10);
                    ap_predicate_pred520_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_F);
                    ap_predicate_pred525_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_E);
                    ap_predicate_pred530_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_D);
                    ap_predicate_pred535_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_C);
                    ap_predicate_pred540_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_B);
                    ap_predicate_pred545_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_A);
                    ap_predicate_pred550_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_9);
                    ap_predicate_pred555_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_8);
                    ap_predicate_pred560_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_7);
                    ap_predicate_pred565_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_6);
                    ap_predicate_pred570_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_5);
                    ap_predicate_pred575_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_4);
                    ap_predicate_pred580_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_3);
                    ap_predicate_pred585_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_2);
                    ap_predicate_pred590_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_1);
                    ap_predicate_pred595_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_0);
                    ap_predicate_pred600_state4 <= (trunc_ln175_reg_953 = ap_const_lv5_1F);
                gmem0_addr_read_reg_962 <= m_axi_gmem0_RDATA;
                j_4_reg_957 <= j_4_fu_828_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln175_fu_788_p2 <= std_logic_vector(unsigned(loc_fu_190) + unsigned(ap_const_lv31_1));
    add_ln178_fu_810_p2 <= std_logic_vector(unsigned(i_fu_182) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(m_axi_gmem0_RVALID, icmp_ln175_reg_924)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln175_reg_924 = ap_const_lv1_1) and (m_axi_gmem0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln175_fu_783_p2)
    begin
        if (((icmp_ln175_fu_783_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, ap_block_pp0_stage0, icmp_ln175_reg_924)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln175_reg_924 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    i_3_fu_816_p3 <= 
        add_ln178_fu_810_p2 when (icmp_ln177_fu_805_p2(0) = '1') else 
        i_fu_182;
    icmp_ln175_fu_783_p2 <= "1" when (signed(zext_ln175_fu_779_p1) < signed(mul)) else "0";
    icmp_ln177_fu_805_p2 <= "1" when (j_fu_186 = a_col) else "0";
    j_4_fu_828_p3 <= 
        ap_const_lv32_0 when (icmp_ln177_reg_943(0) = '1') else 
        j_load_reg_933;
    j_5_fu_834_p2 <= std_logic_vector(unsigned(j_4_fu_828_p3) + unsigned(ap_const_lv32_1));
    localA_32_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_32_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_32_ce1 <= ap_const_logic_1;
        else 
            localA_32_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_32_d1 <= gmem0_addr_read_reg_962;

    localA_32_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred590_state4)
    begin
        if (((ap_predicate_pred590_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_32_we1 <= ap_const_logic_1;
        else 
            localA_32_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_33_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_33_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_33_ce1 <= ap_const_logic_1;
        else 
            localA_33_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_33_d1 <= gmem0_addr_read_reg_962;

    localA_33_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred585_state4)
    begin
        if (((ap_predicate_pred585_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_33_we1 <= ap_const_logic_1;
        else 
            localA_33_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_34_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_34_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_34_ce1 <= ap_const_logic_1;
        else 
            localA_34_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_34_d1 <= gmem0_addr_read_reg_962;

    localA_34_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred580_state4)
    begin
        if (((ap_predicate_pred580_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_34_we1 <= ap_const_logic_1;
        else 
            localA_34_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_35_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_35_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_35_ce1 <= ap_const_logic_1;
        else 
            localA_35_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_35_d1 <= gmem0_addr_read_reg_962;

    localA_35_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred575_state4)
    begin
        if (((ap_predicate_pred575_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_35_we1 <= ap_const_logic_1;
        else 
            localA_35_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_36_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_36_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_36_ce1 <= ap_const_logic_1;
        else 
            localA_36_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_36_d1 <= gmem0_addr_read_reg_962;

    localA_36_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred570_state4)
    begin
        if (((ap_predicate_pred570_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_36_we1 <= ap_const_logic_1;
        else 
            localA_36_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_37_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_37_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_37_ce1 <= ap_const_logic_1;
        else 
            localA_37_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_37_d1 <= gmem0_addr_read_reg_962;

    localA_37_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred565_state4)
    begin
        if (((ap_predicate_pred565_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_37_we1 <= ap_const_logic_1;
        else 
            localA_37_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_38_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_38_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_38_ce1 <= ap_const_logic_1;
        else 
            localA_38_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_38_d1 <= gmem0_addr_read_reg_962;

    localA_38_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred560_state4)
    begin
        if (((ap_predicate_pred560_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_38_we1 <= ap_const_logic_1;
        else 
            localA_38_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_39_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_39_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_39_ce1 <= ap_const_logic_1;
        else 
            localA_39_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_39_d1 <= gmem0_addr_read_reg_962;

    localA_39_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred555_state4)
    begin
        if (((ap_predicate_pred555_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_39_we1 <= ap_const_logic_1;
        else 
            localA_39_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_40_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_40_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_40_ce1 <= ap_const_logic_1;
        else 
            localA_40_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_40_d1 <= gmem0_addr_read_reg_962;

    localA_40_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred550_state4)
    begin
        if (((ap_predicate_pred550_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_40_we1 <= ap_const_logic_1;
        else 
            localA_40_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_41_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_41_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_41_ce1 <= ap_const_logic_1;
        else 
            localA_41_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_41_d1 <= gmem0_addr_read_reg_962;

    localA_41_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred545_state4)
    begin
        if (((ap_predicate_pred545_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_41_we1 <= ap_const_logic_1;
        else 
            localA_41_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_42_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_42_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_42_ce1 <= ap_const_logic_1;
        else 
            localA_42_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_42_d1 <= gmem0_addr_read_reg_962;

    localA_42_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred540_state4)
    begin
        if (((ap_predicate_pred540_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_42_we1 <= ap_const_logic_1;
        else 
            localA_42_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_43_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_43_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_43_ce1 <= ap_const_logic_1;
        else 
            localA_43_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_43_d1 <= gmem0_addr_read_reg_962;

    localA_43_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred535_state4)
    begin
        if (((ap_predicate_pred535_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_43_we1 <= ap_const_logic_1;
        else 
            localA_43_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_44_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_44_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_44_ce1 <= ap_const_logic_1;
        else 
            localA_44_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_44_d1 <= gmem0_addr_read_reg_962;

    localA_44_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred530_state4)
    begin
        if (((ap_predicate_pred530_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_44_we1 <= ap_const_logic_1;
        else 
            localA_44_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_45_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_45_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_45_ce1 <= ap_const_logic_1;
        else 
            localA_45_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_45_d1 <= gmem0_addr_read_reg_962;

    localA_45_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred525_state4)
    begin
        if (((ap_predicate_pred525_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_45_we1 <= ap_const_logic_1;
        else 
            localA_45_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_46_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_46_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_46_ce1 <= ap_const_logic_1;
        else 
            localA_46_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_46_d1 <= gmem0_addr_read_reg_962;

    localA_46_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred520_state4)
    begin
        if (((ap_predicate_pred520_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_46_we1 <= ap_const_logic_1;
        else 
            localA_46_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_47_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_47_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_47_ce1 <= ap_const_logic_1;
        else 
            localA_47_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_47_d1 <= gmem0_addr_read_reg_962;

    localA_47_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred515_state4)
    begin
        if (((ap_predicate_pred515_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_47_we1 <= ap_const_logic_1;
        else 
            localA_47_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_48_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_48_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_48_ce1 <= ap_const_logic_1;
        else 
            localA_48_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_48_d1 <= gmem0_addr_read_reg_962;

    localA_48_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred510_state4)
    begin
        if (((ap_predicate_pred510_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_48_we1 <= ap_const_logic_1;
        else 
            localA_48_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_49_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_49_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_49_ce1 <= ap_const_logic_1;
        else 
            localA_49_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_49_d1 <= gmem0_addr_read_reg_962;

    localA_49_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred505_state4)
    begin
        if (((ap_predicate_pred505_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_49_we1 <= ap_const_logic_1;
        else 
            localA_49_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_50_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_50_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_50_ce1 <= ap_const_logic_1;
        else 
            localA_50_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_50_d1 <= gmem0_addr_read_reg_962;

    localA_50_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred500_state4)
    begin
        if (((ap_predicate_pred500_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_50_we1 <= ap_const_logic_1;
        else 
            localA_50_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_51_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_51_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_51_ce1 <= ap_const_logic_1;
        else 
            localA_51_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_51_d1 <= gmem0_addr_read_reg_962;

    localA_51_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred495_state4)
    begin
        if (((ap_predicate_pred495_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_51_we1 <= ap_const_logic_1;
        else 
            localA_51_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_52_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_52_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_52_ce1 <= ap_const_logic_1;
        else 
            localA_52_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_52_d1 <= gmem0_addr_read_reg_962;

    localA_52_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred490_state4)
    begin
        if (((ap_predicate_pred490_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_52_we1 <= ap_const_logic_1;
        else 
            localA_52_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_53_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_53_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_53_ce1 <= ap_const_logic_1;
        else 
            localA_53_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_53_d1 <= gmem0_addr_read_reg_962;

    localA_53_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred485_state4)
    begin
        if (((ap_predicate_pred485_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_53_we1 <= ap_const_logic_1;
        else 
            localA_53_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_54_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_54_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_54_ce1 <= ap_const_logic_1;
        else 
            localA_54_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_54_d1 <= gmem0_addr_read_reg_962;

    localA_54_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred480_state4)
    begin
        if (((ap_predicate_pred480_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_54_we1 <= ap_const_logic_1;
        else 
            localA_54_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_55_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_55_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_55_ce1 <= ap_const_logic_1;
        else 
            localA_55_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_55_d1 <= gmem0_addr_read_reg_962;

    localA_55_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred475_state4)
    begin
        if (((ap_predicate_pred475_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_55_we1 <= ap_const_logic_1;
        else 
            localA_55_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_56_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_56_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_56_ce1 <= ap_const_logic_1;
        else 
            localA_56_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_56_d1 <= gmem0_addr_read_reg_962;

    localA_56_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred470_state4)
    begin
        if (((ap_predicate_pred470_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_56_we1 <= ap_const_logic_1;
        else 
            localA_56_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_57_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_57_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_57_ce1 <= ap_const_logic_1;
        else 
            localA_57_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_57_d1 <= gmem0_addr_read_reg_962;

    localA_57_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred465_state4)
    begin
        if (((ap_predicate_pred465_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_57_we1 <= ap_const_logic_1;
        else 
            localA_57_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_58_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_58_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_58_ce1 <= ap_const_logic_1;
        else 
            localA_58_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_58_d1 <= gmem0_addr_read_reg_962;

    localA_58_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred460_state4)
    begin
        if (((ap_predicate_pred460_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_58_we1 <= ap_const_logic_1;
        else 
            localA_58_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_59_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_59_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_59_ce1 <= ap_const_logic_1;
        else 
            localA_59_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_59_d1 <= gmem0_addr_read_reg_962;

    localA_59_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred455_state4)
    begin
        if (((ap_predicate_pred455_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_59_we1 <= ap_const_logic_1;
        else 
            localA_59_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_60_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_60_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_60_ce1 <= ap_const_logic_1;
        else 
            localA_60_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_60_d1 <= gmem0_addr_read_reg_962;

    localA_60_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred450_state4)
    begin
        if (((ap_predicate_pred450_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_60_we1 <= ap_const_logic_1;
        else 
            localA_60_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_61_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_61_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_61_ce1 <= ap_const_logic_1;
        else 
            localA_61_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_61_d1 <= gmem0_addr_read_reg_962;

    localA_61_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred445_state4)
    begin
        if (((ap_predicate_pred445_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_61_we1 <= ap_const_logic_1;
        else 
            localA_61_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_62_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_62_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_62_ce1 <= ap_const_logic_1;
        else 
            localA_62_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_62_d1 <= gmem0_addr_read_reg_962;

    localA_62_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred600_state4)
    begin
        if (((ap_predicate_pred600_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_62_we1 <= ap_const_logic_1;
        else 
            localA_62_we1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_address1 <= zext_ln181_fu_853_p1(5 - 1 downto 0);

    localA_ce1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_ce1 <= ap_const_logic_1;
        else 
            localA_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    localA_d1 <= gmem0_addr_read_reg_962;

    localA_we1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_predicate_pred595_state4)
    begin
        if (((ap_predicate_pred595_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            localA_we1 <= ap_const_logic_1;
        else 
            localA_we1 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln175_reg_924, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln175_reg_924 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    trunc_ln175_fu_824_p1 <= i_3_fu_816_p3(5 - 1 downto 0);
    zext_ln175_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loc_fu_190),32));
    zext_ln181_fu_853_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_4_reg_957),64));
end behav;
